(()=>{
'use strict';
const C=window.DividendCore,$=id=>document.getElementById(id);
const KEY='kouheim_portfolio_dividends_v1',CACHE='kouheim_dividend_public_cache_v1',VIEW='kouheim_portfolio_view_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(n,d=2)=>C.finite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:d}):'—';
const money=(n,c='JPY')=>C.finite(n)?(c==='JPY'?'¥':'')+number(n,c==='JPY'?2:4)+(c==='JPY'?'':' '+c):'—';
const pct=n=>C.finite(n)?(n>0?'+':'')+number(n,1)+'%':'—';
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
const currentYear=()=>Number(today().slice(0,4));
const ownerName=o=>C.OWNER[o]||({unknown:'未指定'}[o])||o;
const brokerName=b=>b==='eSmart'?'三菱UFJ eスマート':b==='unknown'?'未指定':b;
let receiptStorageError=false,holdings=[],lots=[],receipts=[],data={series:{}},fetchError='',active='history',yearFocus=null,pending=null;
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').classList.toggle('error',error);}
function read(key,fallback){try{const s=localStorage.getItem(key);return s===null?fallback:JSON.parse(s);}catch{if(key===KEY){receiptStorageError=true;message('保存済みの受取記録を読み込めません。上書きを防ぐため保存を停止しています。「全記録をJSON保存」で元データを保存してください。',true);}return fallback;}}
function loadPrivate(){const h=read('kouheim_portfolio_v2',[]),l=read('kouheim_portfolio_lots_v1',[]),r=read(KEY,[]);holdings=Array.isArray(h)?h:[];lots=Array.isArray(l)?l:[];try{const raw=Array.isArray(r)?r:r.receipts;if(!Array.isArray(raw))throw Error();receipts=raw.map(C.normalizeReceipt);}catch{receiptStorageError=true;receipts=[];message('受取配当の保存形式を読み込めません。元データをJSON保存して確認してください。保有株は変更していません。',true);}}
function setTheme(){let apple=false;try{apple=localStorage.getItem(VIEW)==='apple';}catch{}document.body.classList.toggle('apple-look',apple);$('theme').textContent=apple?'標準に戻す':'Apple株価風';}
function opt(v,label){return`<option value="${esc(v)}">${esc(label)}</option>`;}
function selectOptions(id,values,label,all='すべて'){const el=$(id),old=el.value;el.innerHTML=(all!==null?opt('all',all):'')+values.map(v=>opt(v,label(v))).join('');if([...el.options].some(o=>o.value===old))el.value=old;}
function unique(values){return[...new Set(values.filter(Boolean))].sort();}
function setStockOptions(){const el=$('stock'),old=el.value,query=new URLSearchParams(location.search).get('symbol');const all=new Map();for(const h of holdings)if(/^[0-9A-Z]{4,6}\.[TS]$/.test(h.symbol||''))all.set(h.symbol,(h.name||h.symbol)+' · 保有');for(const [s,r]of Object.entries(data.series||{}))if(!all.has(s))all.set(s,r.name||s);if(query&&/^[0-9A-Z]{4,6}\.[TS]$/.test(query)&&!all.has(query))all.set(query,query+' · 未取得');el.innerHTML=all.size?[...all].map(([s,n])=>opt(s,s+' '+n)).join(''):opt('','保有銘柄・配当データなし');const selected=old||query||holdings[0]?.symbol||'8306.T';if(all.has(selected))el.value=selected;
 selectOptions('refOwner',unique(lots.map(x=>x.owner)),ownerName,'全員');selectOptions('refBroker',unique(lots.map(x=>x.broker)),brokerName,'全口座');selectOptions('refTax',Object.keys(C.TAX),x=>C.TAX[x],'すべて');
}
function metric(caption,value,detail){return`<div class="metric"><div class="caption">${esc(caption)}</div><strong>${esc(value)}</strong><small>${esc(detail||'')}</small></div>`;}
function bars(rows,currency,clickable=false){const max=Math.max(1,...rows.map(r=>C.finite(r.value)?r.value:0));return'<div class="bars">'+rows.map(r=>{const known=C.finite(r.value),label=r.label,display=known?money(r.value,currency):r.missingLabel||'未取得';return`<${clickable?'button':'div'} ${clickable?'type="button" data-year="'+r.year+'"':''} class="bar-item ${known?'':'unknown'} ${yearFocus===r.year?'selected':''}" ${clickable?'aria-label':'title'}="${esc(label+' '+display)}"><span class="bar-value">${esc(known?number(r.value,2):display)}</span><span class="bar-area">${known?`<span class="bar-fill" style="height:${Math.max(1,r.value/max*100).toFixed(2)}%"></span>`:''}</span><span class="bar-label">${esc(label)}</span></${clickable?'button':'div'}>`;}).join('')+'</div>';}
function drawHistory(){
 const symbol=$('stock').value,series=data.series?.[symbol],rows=C.history(series),s=C.stats(rows),currency=series?.currency||'JPY';
 $('historyTitle').textContent=(holdings.find(h=>h.symbol===symbol)?.name||series?.name||symbol||'銘柄')+' の年間配当';
 $('historyMetrics').innerHTML=metric('直近実績・1株配当',money(s.latest,currency),rows.at(-1)?.period+' 決算期')+metric('表示期間の1株配当合計',money(s.value,currency),`${s.known}期の取得済み実績${s.missing?'・欠損 '+s.missing+'期':''}／実際の受取額ではありません`)+metric('年平均増配率',pct(s.growth),s.growth===null?'比較に必要な実績がありません':`${rows[0].period} → ${rows.at(-1).period}（${number(s.span,2)}年間）`);
 $('historyPeriod').textContent=rows.length?`${rows[0].period}〜${rows.at(-1).period}・${rows.length}期分。横にスクロールできます。`:'配当履歴は未取得です。0円としては扱いません。';
 $('historyChart').innerHTML=rows.length?bars(rows.map(r=>({label:r.period.replace('-','/'),value:r.annual})),currency):'<div class="empty">この銘柄の配当履歴がありません。下のYahoo!ファイナンスで確認できます。</div>';
 $('historyTable').innerHTML=rows.map((r,i)=>{const t=i?C.trend(r,rows[i-1]):'—',delta=i&&t!=='期の長さを確認'?C.change(r.annual,rows[i-1].annual):null;return`<tr><td>${esc(r.period.replace('-','/'))}</td><td>${r.annual===null?'未取得':esc(money(r.annual,currency))}</td><td class="${delta>0?'up':delta<0?'down':''}">${esc(pct(delta))}</td><td>${esc(t)}</td></tr>`;}).reverse().join('')||'<tr><td colspan="4">データなし</td></tr>';
 const forecast=series?.forecast;$('forecast').hidden=!forecast;$('forecast').textContent=forecast?`${forecast.period} 会社予想：${money(forecast.annual,currency)}／1株。上のグラフ・合計・増配率には含めていません。`:'';
 const checked=series?.checkedAt?new Date(series.checkedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未取得';const stale=series?.checkedAt&&Date.now()-Date.parse(series.checkedAt)>7*86400000;
 $('historySource').innerHTML='出典：'+(symbol?`<a href="https://finance.yahoo.co.jp/quote/${encodeURIComponent(symbol)}/dividend" target="_blank" rel="noopener noreferrer">Yahoo!ファイナンス 配当情報</a>`:'未選択')+`<br>取得日時：${esc(checked)}${stale?'（古いデータです）':''}${data.failures?.[symbol]?'・最新の取得に失敗し、取得済み分を表示':''}。年間配当は配信元の分割・併合調整後の値です。決算期の変更・特殊配当の内訳・丸め差は出典で確認してください。`;
 $('exportHistory').disabled=!rows.length;
 drawReference();
}
function drawReference(){const symbol=$('stock').value,filters={owner:$('refOwner').value,broker:$('refBroker').value,accountType:$('refTax').value};const selected=lots.filter(l=>l.symbol===symbol&&C.matches({...l,accountType:l.tax},filters));const any=Object.values(filters).some(v=>v&&v!=='all');const holding=holdings.find(h=>h.symbol===symbol);const shares=lots.some(l=>l.symbol===symbol)?selected.reduce((n,l)=>n+(C.finite(l.shares)?l.shares:0),0):!any&&C.finite(holding?.shares)?holding.shares:null;const rows=C.history(data.series?.[symbol]);$('referenceTotal').textContent=C.finite(shares)?`現在の対象株数：${number(shares,3)}株。以下は現在株数固定・税引前の参考値です。`:'この銘柄・条件の保有株数または口座内訳が未登録です。';$('referenceTable').innerHTML=rows.map(r=>`<tr><td>${esc(r.period)}</td><td>${C.finite(shares)&&C.finite(r.annual)?esc(money(shares*r.annual)):'未取得'}</td></tr>`).reverse().join('');}
async function loadHistory(){
 $('reloadHistory').disabled=true;$('loadStatus').textContent='公開配当データを読み込み中…';const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),15000);
 try{const response=await fetch('./dividends-data.json?ts='+Date.now(),{cache:'no-store',credentials:'omit',signal:abort.signal});if(!response.ok)throw Error('HTTP '+response.status);const d=await response.json();if(d.schemaVersion!==1||!d.series||typeof d.series!=='object')throw Error('データ形式を確認できません');data=d;fetchError='';try{localStorage.setItem(CACHE,JSON.stringify(d));}catch{}}
 catch(e){fetchError='通信失敗。'+(Object.keys(data.series||{}).length?'端末の前回取得分を表示します。':'履歴は未取得です。');}
 finally{clearTimeout(timer);$('reloadHistory').disabled=false;setStockOptions();drawHistory();$('loadStatus').textContent=fetchError||`公開履歴 ${Object.keys(data.series||{}).length}銘柄。サーバーの日次更新データを表示しています。`;}
}
function receiptFilters(){return{owner:$('owner').value,broker:$('broker').value,accountType:$('accountType').value,currency:$('currency').value,symbol:$('receiptStock').value};}
function initReceiptFilters(){
 const end=$('endYear'),previous=end.value,now=currentYear(),first=Math.min(now-19,...receipts.map(r=>+r.date.slice(0,4)));end.innerHTML=Array.from({length:Math.min(100,now-first+1)},(_,i)=>opt(now-i,`${now-i-9}〜${now-i}${i===0?'（今年は途中）':''}`)).join('');if([...end.options].some(o=>o.value===previous))end.value=previous;
 selectOptions('currency',unique(['JPY',...receipts.map(r=>r.currency)]),x=>x,null);
 selectOptions('owner',unique([...Object.keys(C.OWNER),...receipts.map(r=>r.owner)]),ownerName,'全員');selectOptions('broker',unique(receipts.map(r=>r.broker)),brokerName,'全口座');selectOptions('accountType',Object.keys(C.TAX),x=>C.TAX[x],'すべて');selectOptions('receiptStock',unique(receipts.map(r=>r.symbol)),x=>x+' '+(receipts.find(r=>r.symbol===x)?.name||''),'全銘柄');
}
function filteredReceipts(){const f=receiptFilters(),end=Number($('endYear').value);return receipts.filter(r=>C.matches(r,f)&&+r.date.slice(0,4)>=end-9&&+r.date.slice(0,4)<=end);}
function drawReceipts(){
 const filters=receiptFilters(),end=Number($('endYear').value),field=$('receiptField').value,currency=filters.currency,rows=C.annualReceipts(receipts,end,field,filters),selected=filteredReceipts(),sum=C.total(selected.map(r=>r[field]));
 $('receiptMetrics').innerHTML=metric('登録済み10年合計 '+(field==='net'?'税引後':'税引前'),money(sum.value,currency),`${end-9}〜${end}・${sum.known}明細分${sum.missing?'／金額不明 '+sum.missing+'件':''}`)+metric('登録のある年',rows.filter(r=>r.count).length+' / 10年','未登録の年は0円ではありません')+metric('対象の受取明細',selected.length+'件','通貨別に集計・予想配当は含みません');
 $('receiptTitle').textContent=`${end-9}〜${end}年の受取配当（${currency}）`;
 $('receiptChart').innerHTML=bars(rows.map(r=>({year:r.year,label:String(r.year),value:r.value,missingLabel:r.count?'金額不明':'未登録'})),currency,true);
 $('receiptTable').innerHTML=rows.map(r=>`<tr class="${yearFocus===r.year?'highlight':''}"><td><button class="year-btn" type="button" data-year="${r.year}">${r.year}${r.year===currentYear()?'（途中）':''}</button></td><td>${r.value===null?(r.count?'金額不明':'未登録'):esc(money(r.value,currency))}</td><td>${r.count?`${r.count}件${r.missing?'・金額不明 '+r.missing+'件':''}`:'記録なし'}</td></tr>`).reverse().join('');
 for(const button of document.querySelectorAll('[data-year]'))button.onclick=()=>{yearFocus=Number(button.dataset.year);drawReceipts();$('detailTitle').scrollIntoView({block:'start'});};
 $('detailTitle').textContent=yearFocus?yearFocus+'年の受取明細':'10年間の受取明細';const list=selected.filter(r=>!yearFocus||+r.date.slice(0,4)===yearFocus);
 $('receiptDetails').innerHTML=list.length?list.map(r=>{const index=receipts.indexOf(r);return`<div class="receipt-row"><div><strong>${esc(r.name||r.symbol)}</strong><div class="muted">${esc(r.date+' · '+r.symbol)}</div><div class="muted">${esc(ownerName(r.owner)+' / '+brokerName(r.broker)+' / '+C.TAX[r.accountType])}</div>${r.note?'<div class="muted">'+esc(r.note)+'</div>':''}</div><div class="money">${r[field]===null?'金額不明':esc(money(r[field],currency))}<small class="muted" style="display:block">税前 ${esc(money(r.gross,currency))}<br>税額 ${esc(money(r.tax,currency))}</small><button type="button" data-delete="${index}">この記録を削除</button></div></div>`;}).join(''):'<div class="empty"><b>受取記録がありません</b>下の「受取配当を読み込む／書き出す」または「受取配当を1件追加」で登録してください。実際の受取額を推測して埋めることはありません。</div>';
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.delete),r=receipts[index];if(r&&confirm(r.date+' '+(r.name||r.symbol)+' の受取記録を削除しますか？保有株は変更しません。')){try{saveReceipts(receipts.filter((_,i)=>i!==index));message('受取記録を1件削除しました。');}catch(e){message(e.message,true);}}});
}
function saveReceipts(next){if(receiptStorageError)throw Error('保存済み記録の読込エラーがあるため、上書きしていません。');try{localStorage.setItem(KEY,JSON.stringify({schemaVersion:1,receipts:next}));}catch{throw Error('端末に保存できませんでした。容量・プライベートブラウズ設定を確認してください。');}receipts=next;initReceiptFilters();drawReceipts();}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function setTab(which){active=which;const h=which==='history';$('historyPanel').hidden=!h;$('receiptsPanel').hidden=h;$('tabHistory').setAttribute('aria-selected',String(h));$('tabReceipts').setAttribute('aria-selected',String(!h));if(!h)drawReceipts();}
function resetPreview(){pending=null;$('importPreview').hidden=true;$('confirmImport').hidden=true;}
function importPreview(){try{const incoming=C.parseInput($('receiptText').value,today()),merged=C.merge(receipts,incoming);pending={incoming,text:$('receiptText').value};$('importPreview').textContent=`${incoming.length}明細を確認しました。追加 ${merged.added}件・重複 ${merged.skipped}件。現在の保有株や既存の配当記録は置き換えません。`;$('importPreview').hidden=false;$('confirmImport').hidden=merged.added===0;$('importPreview').classList.remove('error');}catch(e){resetPreview();$('importPreview').textContent=e.message;$('importPreview').hidden=false;$('importPreview').classList.add('error');}}
loadPrivate();const cached=read(CACHE,{series:{}});if(cached?.series)data=cached;setTheme();setStockOptions();initReceiptFilters();drawHistory();drawReceipts();
$('theme').onclick=()=>{try{localStorage.setItem(VIEW,document.body.classList.contains('apple-look')?'standard':'apple');setTheme();}catch{message('表示設定を保存できませんでした。',true);}};
$('tabHistory').onclick=()=>setTab('history');$('tabReceipts').onclick=()=>setTab('receipts');document.querySelector('.switch').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setTab(active==='history'?'receipts':'history');$(active==='history'?'tabHistory':'tabReceipts').focus();}};
$('stock').onchange=drawHistory;$('reloadHistory').onclick=loadHistory;for(const id of ['refOwner','refBroker','refTax'])$(id).onchange=drawReference;
for(const id of ['endYear','receiptField','currency','owner','broker','accountType','receiptStock'])$(id).onchange=()=>{yearFocus=null;drawReceipts();};$('showAllYears').onclick=()=>{yearFocus=null;drawReceipts();};
$('receiptText').oninput=resetPreview;$('previewImport').onclick=importPreview;
$('receiptFile').onchange=async e=>{resetPreview();const file=e.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw Error('ファイルは2MBまでです');const buffer=await file.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{text=new TextDecoder('shift-jis',{fatal:true}).decode(buffer);}$('receiptText').value=text;importPreview();}catch(error){message('ファイルを読み込めません: '+error.message,true);}};
$('confirmImport').onclick=()=>{try{if(!pending||pending.text!==$('receiptText').value)throw Error('内容が変わりました。もう一度「内容を確認」を押してください。');const merged=C.merge(receipts,pending.incoming);if(!confirm(`${merged.added}件の受取配当をこの端末に追加しますか？`))return;saveReceipts(merged.receipts);resetPreview();$('receiptText').value='';$('receiptFile').value='';message(`受取配当を${merged.added}件追加しました。重複${merged.skipped}件はスキップしました。`);}catch(e){message(e.message,true);}};
$('receiptForm').elements.date.max=today();$('receiptForm').onsubmit=e=>{e.preventDefault();try{const form=Object.fromEntries(new FormData(e.currentTarget)),incoming=C.parseInput(JSON.stringify([form]),today());incoming[0].id=globalThis.crypto?.randomUUID?.()||('manual-'+Date.now()+'-'+Math.random().toString(36).slice(2));const merged=C.merge(receipts,incoming);saveReceipts(merged.receipts);e.currentTarget.reset();$('formStatus').textContent='1件保存しました。';message('受取配当を1件保存しました。');}catch(error){$('formStatus').textContent=error.message;}};
$('template').onclick=()=>download('dividend-receipts-template.csv',C.toCSV([]),'text/csv');
$('exportReceipts').onclick=()=>{let raw;try{raw=localStorage.getItem(KEY);}catch{}download('dividend-receipts-'+today()+'.json',raw||JSON.stringify({schemaVersion:1,receipts},null,2));};
$('exportReceiptCSV').onclick=()=>download('dividend-receipts-filtered-'+today()+'.csv',C.toCSV(filteredReceipts()),'text/csv');
$('exportHistory').onclick=()=>{const s=$('stock').value,rows=C.history(data.series?.[s]);const text='\uFEFFperiod,annual_split_adjusted,currency,source\r\n'+rows.map(r=>[r.period,r.annual??'',data.series[s].currency,`https://finance.yahoo.co.jp/quote/${s}/dividend`].join(',')).join('\r\n');download(s+'-dividend-history.csv',text,'text/csv');};
window.addEventListener('storage',e=>{if(['kouheim_portfolio_v2','kouheim_portfolio_lots_v1',KEY].includes(e.key)){loadPrivate();setStockOptions();initReceiptFilters();drawHistory();drawReceipts();}if(e.key===VIEW)setTheme();});
if(new URLSearchParams(location.search).get('mode')==='receipts')setTab('receipts');loadHistory();
})();
