(()=>{
'use strict';
const C=window.DividendCore,$=id=>document.getElementById(id);
if(!C||!$('sheetBody'))return;
const HOLDINGS_KEY='kouheim_portfolio_v2',LOTS_KEY='kouheim_portfolio_lots_v1',CACHE_KEY='kouheim_dividend_public_cache_v1',VIEW_KEY='kouheim_portfolio_view_v1',STATE_KEY='kouheim_dividend_sheet_v1';
const OWNER_LABEL={all:'全員',OTS:'本人',OKS:'妻',MIK:'MIK',RIN:'RIN'};
const BROKER_LABEL={all:'全口座',SBI:'SBI',eSmart:'eスマート'};
const TAX_LABEL={all:'すべて',nisa:'NISA',oldNisa:'旧NISA',juniorNisa:'ジュニアNISA',specific:'特定',general:'一般',unknown:'区分未判定'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const finite=n=>typeof n==='number'&&Number.isFinite(n);
const num=(n,d=2)=>finite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:d}):'—';
const yen=(n,d=0)=>finite(n)?'¥'+n.toLocaleString('ja-JP',{maximumFractionDigits:d}):'—';
const pct=n=>finite(n)?(n>0?'+':'')+num(n,1)+'%':'—';
const validSymbol=s=>/^[0-9A-Z]{4,6}\.[TS]$/.test(String(s||''));
const safeNumber=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const readJSON=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}};
const writeJSON=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
let holdings=[],lots=[],data={series:{}},fetchError='',queryHandled=false,defaultSelectionPending=false;
let state={years:10,owner:'all',broker:'all',tax:'all',search:'',selected:[],focus:'',view:'overall'};
function normalizeState(raw){const years=Math.max(1,Math.min(10,Number(raw?.years)||10));return{years,owner:Object.hasOwn(OWNER_LABEL,raw?.owner)?raw.owner:'all',broker:Object.hasOwn(BROKER_LABEL,raw?.broker)?raw.broker:'all',tax:Object.hasOwn(TAX_LABEL,raw?.tax)?raw.tax:'all',search:String(raw?.search||'').slice(0,80),selected:Array.isArray(raw?.selected)?raw.selected.filter(validSymbol):[],focus:validSymbol(raw?.focus)?raw.focus:'',view:raw?.view==='individual'?'individual':'overall'};}
function loadLocal(){const h=readJSON(HOLDINGS_KEY,[]),l=readJSON(LOTS_KEY,[]);holdings=Array.isArray(h)?h.map(x=>({symbol:String(x.symbol||'').toUpperCase(),name:String(x.name||''),shares:safeNumber(x.shares)})).filter(x=>validSymbol(x.symbol)):[];lots=Array.isArray(l)?l.map(x=>({symbol:String(x.symbol||'').toUpperCase(),owner:String(x.owner||'').toUpperCase(),broker:String(x.broker||''),tax:String(x.tax||'unknown'),shares:safeNumber(x.shares)})).filter(x=>validSymbol(x.symbol)&&finite(x.shares)&&x.shares>=0):[];}
function saveState(){writeJSON(STATE_KEY,state)}
function setTheme(){let apple=false;try{apple=localStorage.getItem(VIEW_KEY)==='apple'}catch{}document.body.classList.toggle('apple-look',apple);$('theme').textContent=apple?'標準に戻す':'Apple株価風';}
function allUniverse(){const map=new Map();for(const h of holdings)map.set(h.symbol,{symbol:h.symbol,name:h.name||h.symbol,baseShares:h.shares});if(!map.size)for(const [symbol,series] of Object.entries(data.series||{}))if(validSymbol(symbol))map.set(symbol,{symbol,name:series?.name||symbol,baseShares:null});const query=new URLSearchParams(location.search).get('symbol');if(validSymbol(query)&&!map.has(query)){const s=data.series?.[query];map.set(query,{symbol:query,name:s?.name||query,baseShares:null});}return [...map.values()];}
function matchesLot(l){return(state.owner==='all'||l.owner===state.owner)&&(state.broker==='all'||l.broker===state.broker)&&(state.tax==='all'||l.tax===state.tax);}
function sharesFor(item){const own=lots.filter(l=>l.symbol===item.symbol);if(own.length)return own.filter(matchesLot).reduce((n,l)=>n+l.shares,0);if(state.owner==='all'&&state.broker==='all'&&state.tax==='all')return finite(item.baseShares)?item.baseShares:null;return 0;}
function eligibleRows(){const noPrivate=!holdings.length;return allUniverse().map(item=>({...item,shares:sharesFor(item)})).filter(item=>noPrivate?true:finite(item.shares)&&item.shares>0);}
function visibleRows(){const q=state.search.trim().toLowerCase(),rows=eligibleRows();return q?rows.filter(r=>(r.symbol+' '+r.name).toLowerCase().includes(q)):rows;}
function selectedRows(){const set=new Set(state.selected);return eligibleRows().filter(r=>set.has(r.symbol));}
function seriesRows(symbol){return C.history(data.series?.[symbol]);}
function windowRows(symbol){return seriesRows(symbol).slice(-state.years);}
function dividendStats(row){const rows=windowRows(row.symbol),sum=C.total(rows.map(r=>r.annual)),latest=rows.at(-1)?.annual??null,latestRef=finite(latest)&&finite(row.shares)?latest*row.shares:null,periodRef=finite(sum.value)&&finite(row.shares)?sum.value*row.shares:null;return{rows,sum,latest,latestRef,periodRef,growth:C.stats(rows).growth,expected:state.years,known:sum.known,missing:Math.max(0,state.years-sum.known)};}
function ensureSelection(){const universe=allUniverse().map(r=>r.symbol),universeSet=new Set(universe);state.selected=[...new Set(state.selected.filter(s=>universeSet.has(s)))];const query=new URLSearchParams(location.search).get('symbol');if(!queryHandled&&validSymbol(query)){queryHandled=true;state.selected=[query];state.focus=query;state.view='individual';defaultSelectionPending=false;}const eligible=eligibleRows().map(r=>r.symbol);const active=state.selected.filter(s=>eligible.includes(s));if(defaultSelectionPending&&!active.length&&eligible.length){for(const s of eligible)if(!state.selected.includes(s))state.selected.push(s);defaultSelectionPending=false;}const selectedNow=new Set(state.selected);if(!selectedNow.has(state.focus)||!eligible.includes(state.focus))state.focus=eligible.find(s=>selectedNow.has(s))||'';saveState();}
function chipRow(kind,label,values,labels){const current=state[kind];const hasLots=lots.length>0;return`<span class="sheet-filter-label">${esc(label)}</span>${values.map(v=>`<button type="button" class="sheet-chip ${current===v?'on':''}" data-filter="${kind}" data-value="${esc(v)}" ${v!=='all'&&!hasLots?'disabled':''}>${esc(labels[v]||v)}</button>`).join('')}`;}
function metric(caption,value,detail){return`<div class="sheet-metric"><div class="cap">${esc(caption)}</div><strong>${esc(value)}</strong><small>${esc(detail||'')}</small></div>`;}
function relativeLabel(index,total){const back=total-1-index;if(back===0)return'直近期';if(back===1)return'1期前';return`${back}期前`;}
function rowsByRelativePeriod(rows){const selected=rows,columns=Array.from({length:state.years},(_,i)=>({label:relativeLabel(i,state.years),value:0,known:0,total:selected.length}));for(const row of selected){const hist=windowRows(row.symbol),offset=state.years-hist.length;for(let i=0;i<hist.length;i++){const target=columns[offset+i],annual=hist[i]?.annual;if(finite(annual)&&finite(row.shares)){target.value+=annual*row.shares;target.known++;}}}for(const c of columns)if(!c.known)c.value=null;return columns;}
function verticalBars(columns){const values=columns.map(c=>finite(c.value)?c.value:0),max=Math.max(1,...values),minWidth=Math.max(380,columns.length*78);return`<div class="sheet-bars" style="grid-template-columns:repeat(${columns.length},minmax(62px,1fr));min-width:${minWidth}px">${columns.map(c=>`<div class="sheet-bar"><div class="sheet-bar-value">${finite(c.value)?esc(yen(c.value)):'未取得'}</div><div class="sheet-bar-area">${finite(c.value)?`<span class="sheet-bar-fill" style="height:${Math.max(1,c.value/max*100).toFixed(2)}%"></span>`:''}</div><div class="sheet-bar-label">${esc(c.label)}</div><div class="sheet-bar-cover">${c.total?`${c.known}/${c.total}銘柄`:''}</div></div>`).join('')}</div>`;}
function renderFilters(){for(const [id,html] of [['ownerFilters',chipRow('owner','名義',['all','OTS','OKS','MIK','RIN'],OWNER_LABEL)],['brokerFilters',chipRow('broker','証券',['all','SBI','eSmart'],BROKER_LABEL)],['taxFilters',chipRow('tax','口座区分',['all','nisa','oldNisa','juniorNisa','specific','general','unknown'],TAX_LABEL)]])$(id).innerHTML=html;const years=$('sheetYears'),old=String(state.years);years.innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}" ${(i+1)===state.years?'selected':''}>${i+1}年</option>`).join('');if([...years.options].some(o=>o.value===old))years.value=old;$('sheetSearch').value=state.search;$('sheetPeriodLabel').textContent=`直近${state.years}期`;$('periodPerShareHead').textContent=`${state.years}期・1株累計`;$('periodRefHead').textContent=`${state.years}期・参考`;}
function renderTable(){const rows=visibleRows(),selectedSet=new Set(state.selected),activeSelected=selectedRows(),activeSet=new Set(activeSelected.map(r=>r.symbol));$('sheetBody').innerHTML=rows.length?rows.map(row=>{const s=dividendStats(row),partial=s.known<Math.min(state.years,s.rows.length)||s.rows.length<state.years;return`<tr><td class="sheet-check"><input class="sheet-row-check" type="checkbox" data-symbol="${esc(row.symbol)}" ${selectedSet.has(row.symbol)?'checked':''} aria-label="${esc(row.name)}を集計対象にする"></td><td><div class="sheet-stock-main"><div class="sheet-stock-text"><div class="sheet-stock-name">${esc(row.name)}</div><div class="sheet-stock-code">${esc(row.symbol)}</div></div></div></td><td>${finite(row.shares)?esc(num(row.shares,3))+'株':'—'}</td><td>${finite(s.latest)?esc(yen(s.latest,2)):'未取得'}</td><td>${finite(s.latestRef)?esc(yen(s.latestRef)):'—'}</td><td>${finite(s.sum.value)?esc(yen(s.sum.value,2))+(partial?'<span class="sheet-partial">*</span>':''):'未取得'}</td><td>${finite(s.periodRef)?esc(yen(s.periodRef))+(partial?'<span class="sheet-partial">*</span>':''):'—'}</td><td><button class="sheet-focus-btn" type="button" data-focus="${esc(row.symbol)}">個別</button></td></tr>`}).join(''):`<tr><td colspan="8"><div class="sheet-empty"><b>該当する保有銘柄がありません</b>検索または名義・証券・口座区分のフィルターを変更してください。</div></td></tr>`;
 const latest=C.total(activeSelected.map(r=>dividendStats(r).latestRef)),period=C.total(activeSelected.map(r=>dividendStats(r).periodRef));$('sheetFoot').innerHTML=`<tr><th colspan="4">選択合計 ${activeSelected.length}銘柄</th><td>${finite(latest.value)?esc(yen(latest.value)):'—'}</td><td>—</td><td>${finite(period.value)?esc(yen(period.value)):'—'}</td><td></td></tr>`;$('selectionCount').textContent=`選択 ${activeSelected.length}銘柄 / 条件内 ${eligibleRows().length}銘柄 / 表示 ${rows.length}銘柄`;
 const check=$('sheetCheckAll'),visibleSymbols=rows.map(r=>r.symbol),checked=visibleSymbols.filter(s=>selectedSet.has(s)).length;check.checked=!!visibleSymbols.length&&checked===visibleSymbols.length;check.indeterminate=checked>0&&checked<visibleSymbols.length;check.disabled=!visibleSymbols.length;
}
function renderOverall(){const rows=selectedRows();if(!rows.length){$('overallMetrics').innerHTML=metric('選択銘柄','0銘柄','チェックボックスで銘柄を選択してください');$('overallChart').innerHTML='<div class="sheet-empty"><b>集計対象がありません</b>上の保有銘柄シートで銘柄を選んでください。</div>';$('compositionChart').innerHTML='';return;}
 const stats=rows.map(row=>({row,...dividendStats(row)})),latest=C.total(stats.map(s=>s.latestRef)),period=C.total(stats.map(s=>s.periodRef)),known=stats.reduce((n,s)=>n+s.sum.known,0),expected=rows.length*state.years;$('overallMetrics').innerHTML=metric('選択銘柄',`${rows.length}銘柄`,`条件内 ${eligibleRows().length}銘柄`)+metric('直近期の参考配当',finite(latest.value)?yen(latest.value):'未取得',`現在株数固定・${latest.known}/${rows.length}銘柄分`)+metric(`${state.years}期の参考累計`,finite(period.value)?yen(period.value):'未取得',`取得済み実績だけを合計`)+metric('配当履歴の取得率',expected?`${known}/${expected}期`:'—','未取得の期を0円では補いません');$('overallChart').innerHTML=verticalBars(rowsByRelativePeriod(rows));const sorted=stats.slice().sort((a,b)=>(b.periodRef??-1)-(a.periodRef??-1)),max=Math.max(1,...sorted.map(s=>finite(s.periodRef)?s.periodRef:0));$('compositionChart').innerHTML=sorted.map(s=>`<div class="composition-row"><button type="button" class="composition-name" data-focus="${esc(s.row.symbol)}">${esc(s.row.name)}<small>${esc(s.row.symbol)} · ${finite(s.row.shares)?num(s.row.shares,3)+'株':'株数未登録'}</small></button><div class="composition-track">${finite(s.periodRef)?`<div class="composition-fill" style="width:${Math.max(1,s.periodRef/max*100).toFixed(2)}%"></div>`:''}</div><div class="composition-value">${finite(s.periodRef)?esc(yen(s.periodRef)):'未取得'}</div></div>`).join('');}
function renderIndividual(){const rows=selectedRows();if(!rows.length){$('focusStock').innerHTML='<option>選択銘柄なし</option>';$('individualMetrics').innerHTML=metric('個別銘柄','—','上で銘柄を選択してください');$('individualChart').innerHTML='<div class="sheet-empty"><b>個別表示する銘柄がありません</b></div>';$('individualBody').innerHTML='';$('individualSource').textContent='';$('individualForecast').hidden=true;return;}
 if(!rows.some(r=>r.symbol===state.focus))state.focus=rows[0].symbol;const row=rows.find(r=>r.symbol===state.focus),stats=dividendStats(row),hist=stats.rows;$('focusStock').innerHTML=rows.map(r=>`<option value="${esc(r.symbol)}" ${r.symbol===state.focus?'selected':''}>${esc(r.symbol+' '+r.name)}</option>`).join('');$('individualMetrics').innerHTML=metric('現在株数',finite(row.shares)?`${num(row.shares,3)}株`:'—',`${OWNER_LABEL[state.owner]} / ${BROKER_LABEL[state.broker]} / ${TAX_LABEL[state.tax]}`)+metric('直近1株配当',finite(stats.latest)?yen(stats.latest,2):'未取得',hist.at(-1)?.period?hist.at(-1).period+' 決算期':'履歴なし')+metric(`${state.years}期・1株累計`,finite(stats.sum.value)?yen(stats.sum.value,2):'未取得',`${stats.sum.known}期の取得済み実績`)+metric(`${state.years}期・参考配当`,finite(stats.periodRef)?yen(stats.periodRef):'—','現在株数固定・税引前参考');
 $('individualChart').innerHTML=hist.length?verticalBars(hist.map(r=>({label:r.period.replace('-','/'),value:r.annual,known:finite(r.annual)?1:0,total:1}))):'<div class="sheet-empty"><b>配当履歴を取得できません</b>出典リンクから確認してください。</div>';const full=seriesRows(row.symbol);$('individualBody').innerHTML=hist.map((r,i)=>{const globalIndex=full.findIndex(x=>x.period===r.period),prev=globalIndex>0?full[globalIndex-1]:null,t=prev?C.trend(r,prev):'—',delta=prev&&t!=='期の長さを確認'?C.change(r.annual,prev.annual):null,ref=finite(r.annual)&&finite(row.shares)?r.annual*row.shares:null;return`<tr><td>${esc(r.period.replace('-','/'))}</td><td>${finite(r.annual)?esc(yen(r.annual,2)):'未取得'}</td><td>${finite(ref)?esc(yen(ref)):'—'}</td><td class="${delta>0?'up':delta<0?'down':''}">${esc(pct(delta))}</td><td>${esc(t)}</td></tr>`;}).reverse().join('')||'<tr><td colspan="5">配当履歴なし</td></tr>';
 const series=data.series?.[row.symbol],forecast=series?.forecast;$('individualForecast').hidden=!forecast;$('individualForecast').textContent=forecast?`${forecast.period} 会社予想：${finite(forecast.annual)?yen(forecast.annual,2):'未取得'}／1株。実績集計には含めていません。`:'';const checked=series?.checkedAt?new Date(series.checkedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未取得';$('individualSource').innerHTML=`出典：<a href="https://finance.yahoo.co.jp/quote/${encodeURIComponent(row.symbol)}/dividend" target="_blank" rel="noopener noreferrer">Yahoo!ファイナンス 配当情報</a> ／ 取得日時：${esc(checked)}。株式分割・併合調整後の年間配当を使用。`;
 syncLegacyStock(row.symbol);saveState();}
function syncLegacyStock(symbol){const legacy=$('stock');if(!legacy)return;if([...legacy.options].some(o=>o.value===symbol)){legacy.value=symbol;legacy.dispatchEvent(new Event('change',{bubbles:true}));}}
function renderView(){const overall=state.view!=='individual';$('viewOverall').setAttribute('aria-selected',String(overall));$('viewIndividual').setAttribute('aria-selected',String(!overall));$('overallPanel').hidden=!overall;$('individualPanel').hidden=overall;if(overall)renderOverall();else renderIndividual();}
function render(){ensureSelection();renderFilters();renderTable();renderView();const count=Object.keys(data.series||{}).length;$('sheetStatus').textContent=fetchError?fetchError:`公開配当履歴 ${count}銘柄・保有データ ${holdings.length||'未読込'}銘柄`;}
function setFilter(kind,value){if(!['owner','broker','tax'].includes(kind))return;state[kind]=value;ensureSelection();render();saveState();}
function toggleSelection(symbol,checked){const set=new Set(state.selected);checked?set.add(symbol):set.delete(symbol);state.selected=[...set];if(!checked&&state.focus===symbol)state.focus='';ensureSelection();render();saveState();}
async function loadPublic(){const cached=readJSON(CACHE_KEY,null);if(cached?.series){data=cached;render();}$('sheetReload').disabled=true;fetchError='';try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);const res=await fetch('./dividends-data.json?ts='+Date.now(),{cache:'no-store',credentials:'omit',signal:controller.signal});clearTimeout(timer);if(!res.ok)throw Error('HTTP '+res.status);const next=await res.json();if(next?.schemaVersion!==1||!next.series||typeof next.series!=='object')throw Error('形式不明');data=next;writeJSON(CACHE_KEY,next);}catch(e){fetchError=Object.keys(data.series||{}).length?'通信失敗・端末の前回取得分を表示':'配当データを取得できません';}finally{$('sheetReload').disabled=false;render();}}
const savedState=readJSON(STATE_KEY,null);defaultSelectionPending=!Array.isArray(savedState?.selected);state=normalizeState(savedState??state);loadLocal();setTheme();render();
$('theme').onclick=()=>{try{localStorage.setItem(VIEW_KEY,document.body.classList.contains('apple-look')?'standard':'apple')}catch{}setTheme();};
$('sheetReload').onclick=loadPublic;$('sheetYears').onchange=e=>{state.years=Math.max(1,Math.min(10,Number(e.target.value)||10));render();saveState();};
$('sheetSearch').oninput=e=>{state.search=e.target.value.slice(0,80);renderTable();renderView();saveState();};
$('sheetCheckAll').onchange=e=>{const symbols=visibleRows().map(r=>r.symbol),set=new Set(state.selected);for(const s of symbols)e.target.checked?set.add(s):set.delete(s);state.selected=[...set];ensureSelection();render();saveState();};
$('selectVisible').onclick=()=>{const set=new Set(state.selected);for(const r of visibleRows())set.add(r.symbol);state.selected=[...set];render();saveState();};
$('clearVisible').onclick=()=>{const visible=new Set(visibleRows().map(r=>r.symbol));state.selected=state.selected.filter(s=>!visible.has(s));if(visible.has(state.focus))state.focus='';render();saveState();};
$('viewOverall').onclick=()=>{state.view='overall';renderView();saveState();};$('viewIndividual').onclick=()=>{state.view='individual';renderView();saveState();};
$('focusStock').onchange=e=>{state.focus=e.target.value;renderIndividual();saveState();};
document.addEventListener('click',e=>{const filter=e.target.closest('[data-filter]');if(filter&&filter.closest('.sheet-controls'))return setFilter(filter.dataset.filter,filter.dataset.value);const focus=e.target.closest('[data-focus]');if(focus){state.focus=focus.dataset.focus;if(!state.selected.includes(state.focus))state.selected.push(state.focus);state.view='individual';render();saveState();document.querySelector('.sheet-view-switch')?.scrollIntoView({behavior:'smooth',block:'start'});}});
document.addEventListener('change',e=>{if(e.target.matches('.sheet-row-check'))toggleSelection(e.target.dataset.symbol,e.target.checked);});
window.addEventListener('storage',e=>{if([HOLDINGS_KEY,LOTS_KEY].includes(e.key)){loadLocal();render();}if(e.key===VIEW_KEY)setTheme();});
loadPublic();
})();