/* Asset Compass UI. No fetch(), analytics, remote fonts, API keys or cloud sync. */
(function(){
'use strict';
const C=AssetCore,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={dashboard:'ダッシュボード',holdings:'ポートフォリオ',dividends:'配当・入金',forecast:'将来シミュレーション',import:'データを取り込む',consult:'ChatGPTに相談',settings:'名義・保存設定'};
const colors=['#258571','#90cbae','#dfb76b','#638f9c','#abc2d0','#baafcc','#d9cfc2','#b4c5ac','#9da5a3'];
let live=C.empty(),demo=null,view='dashboard',owner='all',year=Number(C.today().slice(0,4)),txFilter='配当・分配金',query='',page=0,hideMoney=false,draft=null,queue=[],paste='',encoding='auto',anonymous=true,question='資産配分と名義別の配当を分析してください。データ不足を明示し、集中リスク・配当収入の見通し・確認すべき点を教えてください。',saveQueue=Promise.resolve(),toastTimer;
const state=()=>demo||live;
const money=(v,unit=true)=>v===null||v===undefined?'—':Math.round(v).toLocaleString('ja-JP')+(unit?'円':'');
const cash=v=>'<span class="money">'+money(v)+'</span>';
const compact=v=>Math.abs(v)>=100000000?(v/100000000).toFixed(2)+'億':Math.abs(v)>=10000?(v/10000).toFixed(v>=1000000?0:1)+'万':Math.round(v).toLocaleString('ja-JP');
const option=(v,label,chosen)=>'<option value="'+esc(v)+'"'+(v===chosen?' selected':'')+'>'+esc(label)+'</option>';
const select=(id,items,chosen,attrs='')=>'<select id="'+id+'" '+attrs+'>'+items.map(x=>option(Array.isArray(x)?x[0]:x,Array.isArray(x)?x[1]:x,chosen)).join('')+'</select>';
const button=(label,action,cls='')=>'<button class="button '+cls+'" data-action="'+action+'">'+label+'</button>';
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function db(action,data){return new Promise((resolve,reject)=>{
 if(!window.indexedDB)return reject(Error('端末保存を利用できません。'));
 const req=indexedDB.open('asset-compass-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('workspace');req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('他のタブを閉じて再試行してください。'));
 req.onsuccess=()=>{const database=req.result;const tx=database.transaction('workspace',action==='get'?'readonly':'readwrite'),store=tx.objectStore('workspace');let value;
 const r=action==='get'?store.get('data'):action==='delete'?store.delete('data'):store.put(data,'data');r.onsuccess=()=>{value=r.result;};tx.oncomplete=()=>{database.close();resolve(value);};tx.onerror=()=>{database.close();reject(tx.error);};tx.onabort=()=>{database.close();reject(tx.error||Error('保存処理が中断されました。'));};};
});}
function storageLabel(text,error=false){$('#storage-status').textContent=text;$('#storage-status').style.color=error?'#b94f52':'';}
function persist(){if(demo){storageLabel('デモ · 保存しません');return;}const snapshot=C.clone(live);storageLabel(snapshot.settings.persist?'保存中…':'今回のみ');saveQueue=saveQueue.catch(()=>{}).then(()=>db(snapshot.settings.persist?'put':'delete',snapshot)).then(()=>storageLabel(live.settings.persist?'端末に保存済み':'今回のみ')).catch(e=>{storageLabel('保存失敗',true);toast('端末保存に失敗しました。バックアップを書き出してください。 '+e.message);});}
function update(next){if(demo)demo=next;else live=next;persist();}
function allOwners(){return [...new Set([...state().settings.members,...state().holdings.map(h=>C.ownerOf(h,state())),...state().transactions.map(t=>C.ownerOf(t,state()))])];}
function ownerOptions(current,allowFollow=false){return (allowFollow?option('','口座設定に従う',current):'')+allOwners().map(o=>option(o,o,current)).join('');}
function filters(withYear=false){let s='<div class="filters"><label class="sr-only" for="owner-filter">集計名義</label>'+select('owner-filter',[['all','家族全体'],...allOwners().map(o=>[o,o])],owner,'aria-label="集計名義"');if(withYear){const years=[...new Set([Number(C.today().slice(0,4)),...state().transactions.map(t=>Number(t.date.slice(0,4)))])].sort((a,b)=>b-a);s+=select('year-filter',years.map(y=>[String(y),y+'年']),String(year),'aria-label="集計年"');}return s+'</div>';}
function head(title,sub,controls=''){return '<div class="page-head"><div><div class="eyebrow">YOUR WEALTH, IN PERSPECTIVE</div><h1>'+title+'</h1><p>'+sub+'</p></div>'+controls+'</div>';}
function metric(label,value,note,cls=''){return '<div class="metric '+cls+'"><div class="metric-label">'+label+'</div><div class="metric-number money">'+money(value,false)+(value===null||value===undefined?'':'<span class="unit">円</span>')+'</div><div class="metric-note">'+note+'</div></div>';}
function panel(title,sub,body,action=''){return '<section class="panel"><div class="panel-head"><div><h2>'+title+'</h2>'+(sub?'<p>'+sub+'</p>':'')+'</div>'+action+'</div>'+body+'</section>';}
function empty(title,msg,action=''){return '<div class="empty"><div class="empty-symbol">◈</div><h3>'+title+'</h3><p>'+msg+'</p>'+action+'</div>';}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';}
function badge(txt,cls=''){return '<span class="badge '+cls+'">'+esc(txt)+'</span>';}
function go(v){view=titles[v]?v:'dashboard';query='';page=0;render();window.scrollTo({top:0,behavior:'instant'});}
function lineChart(series,labels){
 const all=series.flatMap(s=>s.values);if(!all.length)return empty('推移データがありません','「資産推移CSV」を取り込むと、資産合計の変化を表示します。');
 const w=640,h=245,left=55,right=15,top=18,bottom=36,max=Math.max(...all,1)*1.12;
 const x=i=>left+i*(w-left-right)/Math.max(labels.length-1,1),y=v=>h-bottom-v/max*(h-top-bottom);
 let svg='<svg class="chart money" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="資産金額の推移">';
 for(let i=0;i<=4;i++){const value=max*i/4;svg+='<line class="chart-grid" x1="'+left+'" x2="'+(w-right)+'" y1="'+y(value)+'" y2="'+y(value)+'"/><text text-anchor="end" x="'+(left-10)+'" y="'+(y(value)+4)+'">'+compact(value)+'</text>';}
 for(const [n,s]of series.entries()){const pts=s.values.map((v,i)=>x(i)+','+y(v)).join(' ');if(series.length===1&&s.values.length>1)svg+='<polygon points="'+left+','+(h-bottom)+' '+pts+' '+x(s.values.length-1)+','+(h-bottom)+'" fill="'+colors[n]+'" opacity=".08"/>';svg+='<polyline points="'+pts+'" fill="none" stroke="'+(s.color||colors[n])+'" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>';for(let i=0;i<s.values.length;i++)svg+='<circle cx="'+x(i)+'" cy="'+y(s.values[i])+'" r="3" fill="'+(s.color||colors[n])+'"><title>'+esc(labels[i])+': '+money(s.values[i])+'</title></circle>';}
 for(const i of [...new Set([0,Math.floor((labels.length-1)/2),labels.length-1])])svg+='<text text-anchor="'+(i===0?'start':i===labels.length-1?'end':'middle')+'" x="'+x(i)+'" y="'+(h-8)+'">'+esc(labels[i])+'</text>';
 return svg+'</svg>';
}
function donut(groups){
 let parts=Object.entries(groups).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);const total=C.sum(parts,x=>x[1]);if(!total)return empty('残高データを取り込む','保有資産CSVから、資産クラスごとの構成比を表示します。');
 if(parts.length>6)parts=[...parts.slice(0,5),['その他の区分',C.sum(parts.slice(5),x=>x[1])]];let pos=0;
 let svg='<svg class="donut" viewBox="0 0 200 200" role="img" aria-label="資産配分"><circle cx="100" cy="100" r="73" fill="none" stroke="#edf2ef" stroke-width="24"/>';
 parts.forEach(([name,value],i)=>{const pct=value/total*100;svg+='<circle cx="100" cy="100" r="73" fill="none" pathLength="100" stroke="'+colors[i]+'" stroke-width="24" stroke-dasharray="'+Math.max(0,pct-.7)+' '+(100-Math.max(0,pct-.7))+'" stroke-dashoffset="'+(-pos)+'" transform="rotate(-90 100 100)"><title>'+esc(name)+' '+pct.toFixed(1)+'%</title></circle>';pos+=pct;});
 svg+='<text x="100" y="94" text-anchor="middle" font-size="10" fill="#8a9b94">ASSET MIX</text><text x="100" y="118" text-anchor="middle" font-size="23" font-weight="600" fill="#17343a">'+Object.keys(groups).length+'<tspan font-size="10"> 区分</tspan></text></svg>';
 return '<div class="donut-layout">'+svg+'<div class="legend">'+parts.map(([n,v],i)=>'<div class="legend-row"><span class="legend-label"><i class="dot" style="background:'+colors[i]+'"></i>'+esc(n)+'</span><b>'+((v/total)*100).toFixed(1)+'%</b></div>').join('')+'</div></div>';
}
function monthlyBars(s){const max=Math.max(...s.monthActual.map(Math.abs),...s.monthForecast,1);return '<div class="bars money">'+s.monthActual.map((v,i)=>'<div class="bar-group"><div class="bar '+(v<0?'neg':'')+'" style="height:'+Math.max(1,Math.abs(v)/max*100)+'%"><title>'+esc(i+1+'月 実績 '+money(v))+'</title></div><div class="bar forecast" style="height:'+Math.max(1,s.monthForecast[i]/max*100)+'%"><title>'+esc(i+1+'月 年間予測の配分 '+money(s.monthForecast[i]))+'</title></div><span class="bar-label">'+(i+1)+'月</span></div>').join('')+'</div><div class="section-note">濃色：'+year+'年の取込済み実績　淡色：年間予測の入金月別配分<br>予定月へ均等配分した概算です。入金月未設定分 '+cash(s.unscheduled)+' はグラフ外です。</div>';}
function ownerTable(s){return table(['名義','評価額（登録分）','配当実績（選択年）','年間予測・税引後','構成比'],s.byOwner.map((r,i)=>'<tr><td><div class="owner-name"><span class="avatar">'+esc(r.owner.slice(0,1))+'</span><strong>'+esc(r.owner)+'</strong></div></td><td class="num">'+cash(r.value)+'</td><td class="num">'+cash(r.actual)+'</td><td class="num">'+cash(r.forecastNet)+'</td><td style="min-width:85px"><div class="progress-track"><span style="width:'+(s.total?r.value/s.total*100:0)+'%"></span></div></td></tr>'));}
function warnings(s){let msgs=[];if(s.unknownOwners)msgs.push('名義未設定 '+s.unknownOwners+'行：「名義・保存設定」で口座を割り当ててください。');if(s.forecastMissing)msgs.push('配当単価・数量が未設定 '+s.forecastMissing+'資産。予測は設定済み分だけです。');if(s.unknownTax)msgs.push('税区分未設定 '+s.unknownTax+'資産。税引後予測には含めていません。');if(s.dates.length>1)msgs.push('残高の基準日が混在（'+s.dates[0]+'〜'+s.dates.at(-1)+'）。同日残高ではありません。');if(s.excluded)msgs.push('振替・計算対象外・未来日などの配当 '+s.excluded+'件を除外。明細から確認・変更できます。');return msgs.length?'<div class="callout warning">'+msgs.map(m=>'<p>'+esc(m)+'</p>').join('')+'</div>':'';}
function welcome(){return head('家族の資産に、見通しを。','Money Forwardのデータを、資産管理と次の相談につなげます。')+'<section class="welcome"><div class="eyebrow">LESS SPREADSHEETS. MORE PERSPECTIVE.</div><h2>いまの資産も、<br>これからの配当も。</h2><p>家族のポートフォリオをまとめて把握。誰の資産か、いくら配当を受け取ったかを整理し、そのままChatGPTへの相談資料にできます。</p><div class="actions"><button class="button" data-go="import">＋ CSVを取り込んで始める</button>'+button('サンプルで体験する →','demo','ghost')+'</div></section><div class="steps"><div class="step"><div class="number">01 / IMPORT</div><h3>データを持ち込む</h3><p>入出金・保有資産・資産推移のCSV、または表の貼り付け。文字コードと列の違いを確認して取り込みます。</p></div><div class="step"><div class="number">02 / UNDERSTAND</div><h3>名義ごとに見渡す</h3><p>口座を家族の名義に割り当て、資産配分と配当を集計。実績と予測は分けて表示します。</p></div><div class="step"><div class="number">03 / NEXT STEP</div><h3>次の判断を相談する</h3><p>前提とデータ不足を含む相談用Markdown・JSONを出力。名前と口座名を仮名に置き換えられます。</p></div></div><div class="callout">外部への金融データ送信・自動ログインはありません。初期設定では今回のタブ内だけで保持します。端末保存やバックアップは「名義・保存設定」から選べます。</div>';}
function dashboard(){const s=C.summary(state(),owner,year);if(!state().holdings.length&&!state().transactions.length&&!state().history.length)return welcome();const hist=owner==='all'?state().history:[];return head('資産の全体像','取り込んだデータを基に、資産と配当の現在地を確認。',filters(true))+'<div class="metrics">'+metric('資産評価額',s.total,esc(s.totalBasis),'primary')+metric(year+'年 配当受取実績',s.actual,'CSV記載の受取額 · 取込済み期間のみ')+metric('年間配当予測 · 税引後',s.forecastNet,'設定済み・計算可能分 / 今後12か月')+metric('評価損益（取得額あり）',s.costKnown?s.profit:null,'取得額がある '+s.costKnown+' / '+s.holdings.length+' 資産のみ')+'</div>'+warnings(s)+'<div class="grid-two">'+panel('資産の推移','家族全体の資産推移CSV · 入出金を含む残高の変化',lineChart([{values:hist.map(h=>h.total)}],hist.map(h=>h.date.slice(2))),badge(hist.length+' 記録'))+panel('ポートフォリオの構成','保有資産CSVの評価額ベース',donut(s.groups))+'</div>'+panel('名義別の資産と配当','同じ銘柄でも、所有者を分けて集計。未取込は実際の残高ゼロを意味しません。',ownerTable(s),'<button class="button ghost compact" data-go="settings">名義を設定 →</button>')+'<div class="grid-equal">'+panel('月別の配当',year+'年の実績と、設定した年間配当の月配分',monthlyBars(s))+panel('次の確認ポイント','取り込みから、相談までをひとつにつなぐ。','<div class="goal"><span class="symbol">◈</span><div><h3>予測の前提を整える</h3><p>年間配当単価・数量・税区分・入金月を確認。</p></div></div><div style="height:12px"></div><div class="goal"><span class="symbol">✧</span><div><h3>家族の資産を相談する</h3><p>資産配分、配当、データ不足をまとめて出力。</p></div></div><div class="actions" style="margin-top:23px"><button class="button" data-go="holdings">保有資産を編集</button><button class="button primary" data-go="consult">相談データを作る →</button></div>')+'</div>';}
function holdings(){const s=C.summary(state(),owner,year);let hs=s.holdings.filter(h=>[h.name,h.symbol,h.account,C.ownerOf(h,state())].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.valueJPY-a.valueJPY);const rows=hs.slice(page*50,(page+1)*50).map(h=>{const f=C.forecast(h,state());return '<tr><td><strong>'+esc(h.name)+'</strong><span class="sub">'+esc(h.symbol||h.assetClass)+'</span></td><td>'+esc(C.ownerOf(h,state()))+'<span class="sub">'+esc(h.account)+'</span></td><td class="num">'+cash(h.valueJPY)+'</td><td class="num">'+(h.quantity===null?'—':esc(h.quantity.toLocaleString('ja-JP')))+'</td><td class="num">'+cash(h.costJPY===null?null:h.valueJPY-h.costJPY)+'</td><td class="num">'+cash(f.net)+'<span class="sub">'+esc(f.gross===null?'単価・数量未設定':h.taxType)+'</span></td><td>'+esc(h.asOf)+'</td><td><button class="button compact" data-edit-h="'+esc(h.id)+'">編集</button></td></tr>';});return head('ポートフォリオ','保有資産、評価損益、配当予測の前提をまとめて管理。',filters())+'<div class="metrics">'+metric('保有資産合計',s.total,s.holdings.length+' 資産 · 登録残高ベース','primary')+metric('評価損益（判明分）',s.costKnown?s.profit:null,'取得額のない資産は除外')+metric('年間配当 · 税引前',s.forecastGross,'年間配当単価 × 数量 ÷ 基準口数')+metric('年間配当 · 税引後',s.forecastNet,'国内税のみの概算・計算可能分')+'</div>'+warnings(s)+panel('保有資産一覧','証券会社CSVや資産一覧の表を取り込めます。株価の自動更新は行いません。','<div class="actions" style="margin-bottom:15px"><input id="search" type="search" value="'+esc(query)+'" placeholder="銘柄・コード・口座を検索" aria-label="保有資産を検索">'+button('保有資産CSV','export-holdings')+button('＋ 資産を追加','add-holding','primary')+'</div>'+(hs.length?table(['銘柄・資産','名義／口座','評価額','数量','評価損益','年間配当（税引後）','残高基準日',''],rows)+pagination(hs.length):empty('保有資産がありません','入出金CSVだけでは現在の保有数量・評価額は分かりません。保有資産CSVか手入力で追加してください。','<button class="button primary" data-go="import">資産データを取り込む</button>')))+'<div class="callout">年間配当単価は税引前・円単位です。1株配当は基準口数1、1万口あたり分配金は基準口数10,000を設定してください。無配・分配なしは「0」、不明は空欄で区別します。外国源泉税はこの予測に含めません。</div>';}
function pagination(count){return '<div class="pagination"><span>'+count+'件 / '+(page+1)+'ページ</span><button class="button compact" data-page="-1" '+(page===0?'disabled':'')+'>前へ</button><button class="button compact" data-page="1" '+((page+1)*50>=count?'disabled':'')+'>次へ</button></div>';}
function dividends(){const s=C.summary(state(),owner,year);const tx=s.transactions.filter(t=>t.date.slice(0,4)===String(year)&&(txFilter==='all'||txFilter==='excluded'&&C.kindOf(t)==='配当・分配金'&&!C.active(t)||C.kindOf(t)===txFilter)&&[t.description,t.account,t.memo].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));return head('配当と入金を、名義別に。','税引前への逆算はせず、CSV記載の受取額を集計します。',filters(true))+'<div class="metrics">'+metric(year+'年 配当実績',s.actual,s.dividends.length+' 件の集計対象明細','primary')+metric('今後12か月 年間予測',s.forecastNet,'税引後 · 配当単価設定済み分')+metric('直近12か月の配当実績',s.trailingActual,'取込済み実績の単純合計・年換算なし')+metric(year+'年 利息（別集計）',s.interest,'利息は配当の合計に含めません')+'</div>'+warnings(s)+panel('月別の配当実績と年間予測の配分','予定月は権利確定月ではなく入金月を指定します。',monthlyBars(s))+panel('入金明細を確認','自動分類は修正できます。振替・計算対象外・税・元本払戻を配当に自動加算しません。','<div class="tab-strip">'+[['配当・分配金','配当・分配金'],['利息','利息'],['excluded','除外配当'],['all','すべての明細']].map(([v,l])=>'<button class="'+(txFilter===v?'active':'')+'" data-txfilter="'+v+'">'+l+'</button>').join('')+'</div><div class="actions" style="margin-bottom:15px"><input id="search" type="search" value="'+esc(query)+'" placeholder="内容・口座・メモを検索" aria-label="入金明細を検索">'+button('配当明細CSV','export-dividends')+'</div>'+(tx.length?table(['日付','名義／口座','内容','CSV金額','分類','集計状態',''],tx.slice(page*50,(page+1)*50).map(t=>'<tr><td>'+esc(t.date)+'</td><td>'+esc(C.ownerOf(t,state()))+'<span class="sub">'+esc(t.account)+'</span></td><td title="'+esc(t.description)+'">'+esc(t.description.length>30?t.description.slice(0,30)+'…':t.description)+'</td><td class="num">'+cash(t.amountJPY)+'</td><td>'+badge(C.kindOf(t))+'</td><td>'+badge(C.active(t)?'対象':t.date>C.today()?'未来日・除外':t.transfer?'振替・除外':!t.counted?'対象外・除外':'手動除外',C.active(t)?'':'warning')+'</td><td><button class="button compact" data-edit-t="'+esc(t.id)+'">確認</button></td></tr>'))+pagination(tx.length):empty('該当する明細はありません','入出金CSVを取り込むか、表示条件を変更してください。')))+'<div class="callout warning">「配当」の文字を含まない入金は見落とす可能性があります。「すべての明細」も確認してください。別の金融機関・別IDで取得された同じ配当は自動判定できません。証券会社と銀行の二重計上は手動で除外してください。</div>';}
function forecasting(){const s=C.summary(state(),owner,year),p=state().scenario;let chart='',rows='';if(s.total>0){try{const settings=[{label:'控えめ',delta:-p.spread,color:colors[3]},{label:'基準',delta:0,color:colors[0]},{label:'高め',delta:p.spread,color:colors[2]}];const series=settings.map(x=>({...x,rows:C.project(s.total,s.forecastNet||0,{...p,price:p.price+x.delta})}));chart=lineChart(series.map(x=>({values:x.rows.map(r=>r.capital),color:x.color})),series[0].rows.map(r=>r.year+'年後'))+'<div class="scenario-legend">'+settings.map(x=>'<span><i class="dot" style="background:'+x.color+'"></i>'+x.label+' '+(p.price+x.delta)+'%</span>').join('')+'</div>';rows=table(['経過年','控えめ・資産','基準・資産','高め・資産','基準・年間配当','追加積立累計'],series[1].rows.filter(r=>r.year>0).map((r,i)=>'<tr><td>'+r.year+'年後</td><td class="num">'+cash(series[0].rows[r.year].capital)+'</td><td class="num"><strong>'+cash(r.capital)+'</strong></td><td class="num">'+cash(series[2].rows[r.year].capital)+'</td><td class="num">'+cash(r.income)+'</td><td class="num">'+cash(r.contributed)+'</td></tr>'));}catch(e){chart='<div class="callout error">'+esc(e.message)+'</div>';}}else chart=empty('初期資産が必要です','保有資産または資産推移CSVを取り込んでください。');return head('これからの資産を描く。','値上がりと配当を分けて、条件を変えて比較します。',filters())+'<div class="callout warning">これはユーザー入力の仮定によるシミュレーションです。銘柄分析・株価予測・AIの推奨ではありません。未設定の配当は補完せず、税引後が計算できる分だけ使います。</div>'+panel('シミュレーション条件','現金を含む表示対象の総資産に、一律の値上がり率を適用する単純モデルです。','<div class="form-grid">'+field('毎月末の追加積立（円）','sc-monthly',p.monthly,'number','min="0" max="100000000"')+field('値上がり率（年率%・配当を除く）','sc-price',p.price,'number','min="-90" max="100" step="0.1"')+field('増配率（年率%）','sc-dividend',p.dividend,'number','min="-90" max="100" step="0.1"')+field('比較シナリオの差（±%ポイント）','sc-spread',p.spread,'number','min="0" max="30" step="0.1"')+field('期間（年）','sc-years',p.years,'number','min="1" max="50" step="1"')+'<label class="field">配当の扱い'+select('sc-reinvest',[['true','税引後配当を再投資'],['false','受取配当は資産から取り出す']],String(p.reinvest))+'</label></div><div class="actions">'+button('この条件で計算','run-forecast','primary')+'<span class="small muted">初期資産 '+cash(s.total)+' / 初年度配当の基礎額 '+cash(s.forecastNet)+'</span></div>')+panel('将来資産の比較','3本の線は確率や信頼区間ではなく、異なる入力条件です。',chart)+panel('年ごとの見通し','円単位に丸めて表示。毎月末積立、配当も毎月均等に受け取る仮定。',rows||'<p class="muted">計算結果はありません。</p>')+'<div class="section-note">計算方法：値上がり率を月利へ変換し、月末に積立と再投資配当を加算。増配率は年ごとに適用します。追加購入分の配当は初期の「計算可能な税引後配当 ÷ 総資産」の利回りで加算する近似です。売却時の譲渡税・インフレ・手数料・減配や価格の変動経路は未考慮。配当を再投資しない場合は受取額を将来資産に含めません。</div>';}
function field(label,id,value='',type='text',attrs=''){return '<label class="field">'+label+'<input id="'+id+'" type="'+type+'" value="'+esc(value??'')+'" '+attrs+'></label>';}
function importPage(){return head('データを、ひとつの視界へ。','CSV・TSV・表の貼り付けに対応。XLS／XLSX／PDFはCSVに変換して取り込んでください。')+'<div class="callout"><b>入出金CSVだけでは、現在の保有資産は復元できません。</b><p>配当実績には入出金CSV、銘柄別ポートフォリオには保有資産一覧、資産推移には資産合計の履歴が必要です。Money Forwardの資産一覧は表をコピーして貼り付ける方法も使えます。</p></div>'+(!draft?panel('1. ファイルまたは表を選択','CSVは複数ファイルを選択でき、1つずつ内容を確認して取り込みます。','<div class="actions"><label class="field">文字コード'+select('encoding',[['auto','自動判定（UTF-8 / Shift_JIS）'],['utf-8','UTF-8'],['shift_jis','Shift_JIS'],['utf-16le','UTF-16 LE']],encoding)+'</label>'+button('保有資産テンプレートCSV','template')+'</div><div class="drop-zone" id="drop-zone"><div class="upload-icon">⇧</div><h3>ファイルを選択・ドロップ</h3><p>金融データはサーバーにアップロードされません。</p><input id="import-files" type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values" multiple aria-label="CSVファイルを選択"></div><details><summary>表やCSVテキストを貼り付ける</summary><p class="section-note">見出し行からコピーしてください。異なる種類の表は別々に取り込みます。</p><textarea id="paste-csv" placeholder="日付,内容,金額（円）,保有金融機関,…">'+esc(paste)+'</textarea><div class="actions" style="margin-top:12px">'+button('貼り付け内容を確認','parse-paste','primary')+'</div></details>'):draftPanel())+panel('対応するデータ','金融機関によって列名が異なる場合は、取込画面で列を選び直せます。',table(['種類','最低限必要な列','用途'],['<tr><td>入出金</td><td>日付・金額</td><td>名義別・年別・月別の配当、利息</td></tr>','<tr><td>保有資産</td><td>銘柄名またはコード・評価額</td><td>資産配分、評価損益、配当予測</td></tr>','<tr><td>資産推移</td><td>日付・資産合計</td><td>家族全体の資産推移グラフ</td></tr>']))+(state().imports.length?panel('取込履歴','バックアップ復元以外の取り込みを記録します。',table(['日時','ファイル','種類','追加','更新','重複','除外'],state().imports.slice(-15).reverse().map(i=>'<tr><td>'+esc(new Date(i.at).toLocaleString('ja-JP'))+'</td><td>'+esc(i.source)+'</td><td>'+esc(typeName(i.type))+'</td><td>'+i.added+'</td><td>'+i.updated+'</td><td>'+i.duplicate+'</td><td>'+i.skipped+'</td></tr>'))):'');}
function typeName(t){return {transactions:'入出金',holdings:'保有資産',history:'資産推移'}[t]||t;}
function resultDraft(){return C.normalize(draft.parsed,draft.type,draft.map,{owner:draft.owner,account:draft.account,asOf:draft.asOf,assetClass:draft.assetClass,taxType:draft.taxType,source:draft.source});}
function draftPanel(){let r;try{r=resultDraft();}catch(e){return '<div class="callout error">'+esc(e.message)+'</div>'+button('取り込みを中止','cancel-import');}const fields=Object.keys(C.FIELDS[draft.type]);const preview=r.records.slice(0,8).map(x=>'<tr><td>'+esc(x.date||x.asOf)+'</td><td>'+esc(x.owner||'口座設定に従う')+'</td><td>'+esc(x.account||'家族全体')+'</td><td>'+esc(x.description||x.name||'資産合計')+'</td><td class="num">'+cash(x.amountJPY??x.valueJPY??x.total)+'</td></tr>');return panel('2. 内容と名義を確認',esc(draft.source)+' · '+draft.parsed.rows.length+'行 / 待機中 '+queue.length+'ファイル','<div class="form-grid"><label class="field">データの種類'+select('imp-type',[['transactions','入出金'],['holdings','保有資産'],['history','資産推移']],draft.type)+'</label><label class="field">このファイルの名義（CSVの名義を優先）<select id="imp-owner">'+ownerOptions(draft.owner,true)+'</select></label>'+field('口座列がない場合の口座名','imp-account',draft.account)+ (draft.type==='holdings'?field('残高の基準日（列がない場合）','imp-asof',draft.asOf,'date')+'<label class="field">資産区分（列がない場合）'+select('imp-class',C.CLASSES,draft.assetClass)+'</label><label class="field">税区分（列がない場合）'+select('imp-tax',[C.UNKNOWN,'課税','NISA'],draft.taxType)+'</label>':'')+'</div>'+(draft.type==='holdings'?'<label class="field wide">既存の保有資産との合わせ方'+select('imp-mode',[['merge','個別資産を追加・更新（売却済み資産は残ります）'],['accounts','登場する名義・口座の保有資産を全て入れ替える'],['all','保有資産を全件入れ替える']],draft.mode)+'</label><p class="section-note">口座ごとの入れ替えは、その口座の全銘柄・現金がCSVに含まれる場合だけ選択してください。入出金明細は消えません。</p>':'')+(draft.type==='history'?'<div class="callout warning">資産推移は「家族全体の合計」として取り込みます。各人の履歴を混ぜて取り込まないでください。同じ日付は最新の取込値で更新します。残高とは二重加算しません。</div>':'')+'<details><summary>列の対応を確認・変更する（自動判定）</summary><div class="form-grid">'+fields.map(k=>'<label class="field">'+esc(C.LABELS[k])+'<select data-map="'+k+'">'+option('-1','この列は使わない',String(draft.map[k]))+draft.parsed.headers.map((h,i)=>option(String(i),h,String(draft.map[k]))).join('')+'</select></label>').join('')+'</div></details><hr class="divider"><div class="actions">'+badge('有効 '+r.records.length+'件')+badge('除外 '+r.skipped+'件',r.skipped?'warning':'')+badge('確認事項 '+r.issues.length+'件',r.issues.length?'warning':'')+'</div><div class="preview" style="margin-top:15px">'+table(['日付','名義','口座','内容／銘柄','円換算金額'],preview)+'</div>'+(r.issues.length?'<div class="issues">'+r.issues.slice(0,40).map(i=>'<div>行 '+esc(i.row)+'：'+esc(i.message)+'</div>').join('')+(r.issues.length>40?'<div>ほか '+(r.issues.length-40)+'件</div>':'')+'</div>':'')+'<div class="callout warning" style="margin-top:18px">除外行・名義・金額・文字化けを確認してください。不足情報は推定せず未設定のまま残します。外貨は「通貨」と1外貨あたりの「円換算レート」が必要です。既に円換算済みのデータには通貨JPYを使用してください。</div><div class="actions"><button class="button primary" data-action="commit-import" '+(!r.records.length?'disabled':'')+'>確認して '+r.records.length+'件を取り込む</button>'+button('このファイルを中止','cancel-import')+'</div>');}
function consult(){const pack=C.consultation(state(),{owner,year,anonymous,question});return head('相談しやすいデータへ。','資産・配当・予測の前提を、人にもAIにも読みやすく整理。',filters(true))+'<div class="consult-banner"><div><h2>データを整えてから、ChatGPTに。</h2><p>実績・予測・不明点を区別したMarkdown／JSONを作成します。外部への自動送信やAI APIの呼び出しは行いません。</p></div><div class="spark">✧</div></div>'+panel('相談データの設定','配当明細は全取込年から投資関連だけを収録。生活費などの通常明細は相談用出力に含めません。','<label class="field">相談したいこと<textarea id="question" style="min-height:95px">'+esc(question)+'</textarea></label><div class="settings-row"><div><h3>名前と口座名を仮名に置き換える</h3><p>名義A・口座01などへ置換。内容・メモ・ファイル名を省略し、銘柄はコードまたは資産区分で表示します。</p></div><input id="anonymous" type="checkbox" '+(anonymous?'checked':'')+' aria-label="相談データを仮名化"></div><p class="section-note">金額・日付・銘柄コードから個人が推測される可能性は残ります。相談文に書いた個人情報は自動置換しません。送信前に内容を確認してください。</p><div class="actions" style="margin-top:19px">'+button('相談文を更新','refresh-consult')+button('相談文をコピー','copy-consult','primary')+button('Markdownを保存','export-markdown')+button('相談用JSONを保存','export-consult-json')+'</div>')+panel('ChatGPTに渡す相談文','コピーした文章を貼り付けるか、保存したファイルを相談に添えてください。','<textarea id="consult-output" class="code-output" readonly aria-label="相談用Markdown">'+esc(C.markdown(pack))+'</textarea>')+'<div class="callout">ここで作るJSONは相談用です。設定や全明細を復元するには「名義・保存設定」から復元用バックアップを作成してください。</div>';}
function settingsPage(){const s=state(),accounts=[...new Set([...s.holdings,...s.transactions].map(r=>r.account))].sort();return head('名義とデータを整える。','金融機関の口座名を、家族の名義に結び付けます。')+panel('名義メンバー','CSVに名義がある場合はその値を優先。口座名だけで名義を推測しません。','<div class="form-grid">'+s.settings.members.map((m,i)=>'<label class="field">名義 '+(i+1)+'<input data-member="'+i+'" value="'+esc(m)+'" maxlength="40"></label>').join('')+'</div>'+button('＋ 名義を追加','add-member'))+panel('口座と名義の対応','この設定は保有資産と入出金の両方に適用されます。CSV名義や明細の個別設定が優先されます。',accounts.length?table(['口座名（CSVの表記）','名義','登録行数'],accounts.map(a=>'<tr><td>'+esc(a)+'</td><td><select data-account="'+esc(a)+'">'+option('',C.UNKNOWN,s.settings.accountOwners[a]||'')+s.settings.members.map(m=>option(m,m,s.settings.accountOwners[a]||'')).join('')+'</select></td><td>'+[...s.holdings,...s.transactions].filter(r=>r.account===a).length+'</td></tr>')):empty('口座はまだありません','CSVを取り込むと、口座名がここに並びます。'))+panel('保存とバックアップ','端末を変える場合はバックアップの書き出し・読み込みで移します。自動同期はありません。','<div class="settings-row"><div><h3>この端末に保存する（暗号化なし）</h3><p>オンにすると同じブラウザで開き直せます。オフにすると保存済みデータを消し、このタブだけで保持します。</p></div><input id="persist-toggle" type="checkbox" '+(s.settings.persist?'checked':'')+' '+(demo?'disabled':'')+' aria-label="この端末に保存する"></div><div class="callout warning" style="margin-top:17px">端末内保存にログイン認証・暗号化はありません。同じブラウザの利用者や同一ドメインのスクリプトから読まれる可能性があります。ブラウザのデータ削除・保存容量不足・プライベートモードによる消失にも備え、バックアップを保管してください。</div><div class="actions">'+button('復元用バックアップ','backup','primary')+button('バックアップを読み込む','restore')+'</div>')+panel('予測用の税率','課税区分に使う国内税率の試算パラメータです。NISAは国内税0。税務申告用の計算ではありません。','<div class="form-grid">'+field('予測の課税率（%）','tax-rate',s.settings.taxRate,'number','min="0" max="100" step="0.001"')+'</div>'+button('税率を保存','save-tax')+'<p class="section-note">外国源泉税・受取方法による違い・手数料・税計算の端数は別途確認が必要です。実績の受取金額へこの税率を再適用することはありません。</p>')+panel('データの初期化','実データを削除する前に、必要なバックアップを保存してください。','<div class="actions">'+button('すべてのデータを削除','clear','danger')+button('架空データで体験','demo')+'</div>');}
function render(){
 $('#breadcrumb').textContent=titles[view];document.querySelectorAll('#nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});$('#demo-banner').hidden=!demo;
 const fn={dashboard,holdings,dividends,forecast:forecasting,import:importPage,consult,settings:settingsPage}[view];
 try{$('#main').innerHTML=fn();}catch(e){$('#main').innerHTML='<div class="callout error">表示できませんでした：'+esc(e.message)+'</div><button class="button" data-go="settings">設定を開く</button>';console.error(e);}
 document.body.classList.toggle('hide-money',hideMoney);bindDrop();
}
function showModal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function editHolding(id){const h=state().holdings.find(r=>r.id===id)||{id:'',name:'',symbol:'',account:'手入力口座',owner:'',assetClass:'国内株式',quantity:null,valueJPY:null,costJPY:null,annualDps:null,dividendUnit:1,months:[],taxType:C.UNKNOWN,asOf:C.today()};showModal('<h2>'+ (h.id?'保有資産を編集':'保有資産を追加')+'</h2><div class="form-grid two">'+field('銘柄名・資産名','h-name',h.name)+field('銘柄コード（任意）','h-symbol',h.symbol)+field('口座名','h-account',h.account)+'<label class="field">名義（個別指定）<select id="h-owner">'+ownerOptions(h.owner,true)+'</select></label><label class="field">資産区分'+select('h-class',C.CLASSES,h.assetClass)+'</label><label class="field">税区分'+select('h-tax',[C.UNKNOWN,'課税','NISA'],h.taxType)+'</label>'+field('評価額・残高（円）','h-value',h.valueJPY,'number','min="0" step="any" required')+field('取得金額の総額（円・不明は空欄）','h-cost',h.costJPY,'number','min="0" step="any"')+field('保有数量（株・口）','h-quantity',h.quantity,'number','min="0" step="any"')+field('年間配当単価（税引前・円）','h-dps',h.annualDps,'number','min="0" step="any"')+field('配当の基準口数（株=1 / 投信=10000）','h-unit',h.dividendUnit,'number','min="0.000001" step="any"')+field('入金予定月（例：6,12）','h-months',h.months.join(','))+field('残高の基準日','h-date',h.asOf,'date')+'</div><p class="section-note">配当不明は空欄、無配は0。年間総配当ではなく、1株または基準口数あたりの年間単価を入力します。</p><div class="modal-actions">'+(h.id?'<button class="button danger" data-delete-h="'+esc(h.id)+'">削除</button>':'')+'<button class="button" data-action="close-modal">キャンセル</button><button class="button primary" data-save-h="'+esc(h.id)+'">保存</button></div>');}
function saveHolding(id){const read=x=>$('#h-'+x).value,h={id:id||C.uid(),name:read('name').trim(),symbol:read('symbol').trim(),account:read('account').trim(),owner:read('owner'),assetClass:read('class'),taxType:read('tax'),valueJPY:C.num(read('value')),costJPY:C.num(read('cost')),quantity:C.num(read('quantity')),annualDps:C.num(read('dps')),dividendUnit:C.num(read('unit')),months:C.months(read('months')),asOf:C.date(read('date')),currency:'JPY',fx:1};if(!h.name||!h.account||h.valueJPY===null||h.valueJPY<0||!h.asOf||!h.dividendUnit||h.dividendUnit<=0||[h.costJPY,h.quantity,h.annualDps].some(v=>v!==null&&v<0)){toast('銘柄名・口座・0以上の金額・有効な基準日と基準口数を入力してください。');return;}const n=C.clone(state()),old=n.holdings.find(x=>x.id===id);h.key=old?.key||JSON.stringify([h.owner,h.account,h.symbol||h.name,h.taxType])+':1';if(old)Object.assign(old,h);else{if(n.holdings.some(x=>x.key===h.key)){toast('同じ名義・口座・銘柄が登録されています。既存行を編集してください。');return;}n.holdings.push(h);}update(n);closeModal();render();toast('保有資産を保存しました。');}
function editTransaction(id){const t=state().transactions.find(x=>x.id===id);if(!t)return;showModal('<h2>入金明細の確認・修正</h2><p><b>'+esc(t.date)+' · '+cash(t.amountJPY)+'</b><br>'+esc(t.description)+'</p><p class="section-note">口座：'+esc(t.account)+'<br>元の大項目・中項目：'+esc(t.category)+' / '+esc(t.subcategory)+'<br>計算対象：'+(t.counted?'1':'0')+' / 振替：'+(t.transfer?'1':'0')+'</p><div class="form-grid two"><label class="field">分類'+select('t-kind',C.KINDS,C.kindOf(t))+'</label><label class="field">名義<select id="t-owner">'+ownerOptions(t.owner,true)+'</select></label><label class="field wide">集計対象'+select('t-include',[['auto','CSVの計算対象・振替に従う'],['yes','手動で含める（未来日は含めません）'],['no','手動で除外する']],t.includeOverride===true?'yes':t.includeOverride===false?'no':'auto')+'</label></div><p class="section-note">金額と日付は原票を保持します。元本払戻・税・利息を「配当」に変更する前に取引内容を確認してください。</p><div class="modal-actions"><button class="button" data-action="close-modal">キャンセル</button><button class="button primary" data-save-t="'+esc(id)+'">保存</button></div>');}
function saveTransaction(id){const n=C.clone(state()),t=n.transactions.find(x=>x.id===id);if(!t)return;t.kindOverride=$('#t-kind').value;t.owner=$('#t-owner').value;const v=$('#t-include').value;if(v==='auto')delete t.includeOverride;else t.includeOverride=v==='yes';update(n);closeModal();render();toast('明細の分類・名義・集計状態を更新しました。');}
function download(content,name,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportHoldings(){const s=state(),rows=C.selected(s.holdings,s,owner);download(C.csv(['名義','口座','資産区分','銘柄コード','銘柄名','評価額（円）','取得金額（円）','数量','年間配当単価（円）','配当基準口数','入金予定月','税区分','基準日'],rows.map(h=>[C.ownerOf(h,s),h.account,h.assetClass,h.symbol,h.name,h.valueJPY,h.costJPY,h.quantity,h.annualDps,h.dividendUnit,h.months.join('/'),h.taxType,h.asOf])),'保有資産_'+C.today()+'.csv','text/csv;charset=utf-8');}
function exportDividends(){const s=state(),rows=C.selected(s.transactions,s,owner).filter(t=>C.kindOf(t)==='配当・分配金');download(C.csv(['日付','名義','口座','内容','金額（円）','分類','集計に含める','計算対象','振替'],rows.map(t=>[t.date,C.ownerOf(t,s),t.account,t.description,t.amountJPY,C.kindOf(t),C.active(t)?1:0,t.counted?1:0,t.transfer?1:0])),'配当明細_全年_'+C.today()+'.csv','text/csv;charset=utf-8');}
function template(){download(C.csv(['名義','口座','資産区分','銘柄コード','銘柄名','評価額（円）','取得金額（円）','数量','年間配当単価（円）','配当基準口数','入金予定月','税区分','基準日'],[['夫','証券口座A','国内株式','DEMO','入力例（実データに置換）',100000,80000,100,30,1,'6/12','課税',C.today()]]),'保有資産_入力テンプレート.csv','text/csv;charset=utf-8');}
function startFiles(files){if(demo){if(!confirm('デモを終了して実データの取り込みに切り替えます。よろしいですか？'))return;demo=null;storageLabel(live.settings.persist?'端末に保存済み':'今回のみ');}queue=Array.from(files);nextFile();}
async function nextFile(){draft=null;if(!queue.length){render();return;}const f=queue.shift();try{if(!/\.(csv|tsv|txt)$/i.test(f.name))throw Error('CSV・TSV・TXTを選択してください。ExcelはCSVで保存してください。');if(f.size>20000000)throw Error('20MB以下のファイルに分割してください。');const buffer=await f.arrayBuffer(),parsed=C.parseCSV(C.decode(buffer,encoding));newDraft(parsed,f.name);render();}catch(e){toast(f.name+'：'+e.message);if(queue.length)await nextFile();else render();}}
function newDraft(parsed,source){const type=C.detect(parsed.headers);draft={parsed,source,type,map:C.mapping(parsed.headers,type),owner:'',account:'',asOf:C.today(),assetClass:'その他',taxType:C.UNKNOWN,mode:'merge'};view='import';}
function bindDrop(){const d=$('#drop-zone');if(!d)return;d.ondragover=e=>{e.preventDefault();d.classList.add('drag');};d.ondragleave=()=>d.classList.remove('drag');d.ondrop=e=>{e.preventDefault();d.classList.remove('drag');startFiles(e.dataTransfer.files);};}
function commitImport(){if(!draft)return;const r=resultDraft();if(!r.records.length)return;if(draft.type==='holdings'&&draft.mode!=='merge'&&!confirm('保有資産を「'+(draft.mode==='all'?'全件':'CSVに登場する名義・口座ごと')+'」入れ替えます。CSVにない銘柄は削除されます。続けますか？'))return;const result=C.applyImport(state(),r,draft.mode,draft.source);update(result.state);toast('追加 '+result.added+'件 / 更新 '+result.updated+'件 / 同一明細 '+result.duplicate+'件 / 除外 '+r.skipped+'件');nextFile();}
function forecastRun(){const v=k=>Number($('#sc-'+k).value),p={monthly:v('monthly'),price:v('price'),dividend:v('dividend'),spread:v('spread'),years:v('years'),reinvest:$('#sc-reinvest').value==='true'};if(!Object.values(p).filter(v=>typeof v==='number').every(Number.isFinite)||p.monthly<0||p.spread<0||p.spread>30||p.price-p.spread<=-100||p.price>100||p.dividend<=-100||p.dividend>100||!Number.isInteger(p.years)||p.years<1||p.years>50){toast('数値の範囲を確認してください。期間は1〜50年です。');return;}const n=C.clone(state());n.scenario=p;update(n);render();}
function pack(){return C.consultation(state(),{owner,year,anonymous,question});}
function updateConsultInput(){if($('#question'))question=$('#question').value;if($('#anonymous'))anonymous=$('#anonymous').checked;}
async function copyConsult(){updateConsultInput();const out=C.markdown(pack());try{await navigator.clipboard.writeText(out);toast('相談文をコピーしました。ChatGPTに貼り付けてください。');}catch{$('#consult-output').value=out;$('#consult-output').focus();$('#consult-output').select();toast('文章を選択しました。端末の「コピー」を選んでください。');}}
function backupModal(){showModal('<h2>復元用バックアップ</h2><div class="callout warning">全明細・名義・口座名を含むファイルです。相談用出力とは異なり個人情報を含みます。安全な場所に保管してください。</div><label class="field">暗号化用パスワード（12文字以上）<input id="backup-password" type="password" autocomplete="new-password" minlength="12"></label><p class="section-note">暗号化にはAES-GCMとPBKDF2を使用します。パスワードを失うと復元できません。端末内保存の暗号化ではなく、書き出すファイルの暗号化です。</p><div class="modal-actions"><button class="button" data-action="close-modal">閉じる</button><button class="button" data-action="backup-plain">暗号化なしで保存</button><button class="button primary" data-action="backup-encrypted">暗号化して保存</button></div>');}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=16384)s+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(s);}
function base64ToBytes(s){const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0));}
async function cryptoKey(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:210000},key,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encryptBackup(){const password=$('#backup-password').value;if(password.length<12){toast('12文字以上のパスワードを入力してください。');return;}if(!crypto.subtle){toast('このブラウザでは暗号化を利用できません。HTTPSで開いてください。');return;}try{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(password,salt),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(state())));download(JSON.stringify({format:'asset-compass-encrypted/v1',iterations:210000,salt:bytesToBase64(salt),iv:bytesToBase64(iv),data:bytesToBase64(new Uint8Array(data))}),'資産バックアップ_暗号化_'+C.today()+'.json','application/json');closeModal();toast('暗号化バックアップを書き出しました。');}catch(e){toast('暗号化に失敗しました：'+e.message);}}
function plainBackup(){if(!confirm('個人情報を含む暗号化されていないJSONを書き出します。よろしいですか？'))return;download(JSON.stringify(state(),null,2),'資産バックアップ_個人情報あり_'+C.today()+'.json','application/json');closeModal();}
let encryptedRestore=null;
async function restoreFile(f){if(!f)return;try{if(f.size>40000000)throw Error('40MB以下のバックアップを選択してください。');const obj=JSON.parse(await f.text());if(obj.format==='asset-compass-encrypted/v1'){if(obj.iterations!==210000)throw Error('未対応の暗号化形式です。');encryptedRestore=obj;showModal('<h2>暗号化バックアップを復元</h2><label class="field">パスワード<input id="restore-password" type="password" autocomplete="current-password"></label><div class="modal-actions"><button class="button" data-action="close-modal">キャンセル</button><button class="button primary" data-action="decrypt-restore">復号して確認</button></div>');return;}restoreObject(obj);}catch(e){toast('復元できません：'+e.message);}finally{$('#restore-file').value='';}}
async function decryptRestore(){try{const salt=base64ToBytes(encryptedRestore.salt),iv=base64ToBytes(encryptedRestore.iv);if(salt.length!==16||iv.length!==12)throw Error('暗号化形式が不正です。');const key=await cryptoKey($('#restore-password').value,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64ToBytes(encryptedRestore.data)),obj=JSON.parse(new TextDecoder().decode(plain));closeModal();restoreObject(obj);encryptedRestore=null;}catch{toast('復号できません。パスワードまたはファイルを確認してください。');}}
function restoreObject(obj){const next=C.validateBackup(obj);if(!confirm('現在の実データをバックアップで置き換えます。保有資産 '+next.holdings.length+'件、入出金 '+next.transactions.length+'件。続けますか？'))return;demo=null;next.settings.persist=live.settings.persist;update(next);owner='all';go('dashboard');toast('バックアップを復元しました。');}
function renameMember(index,name){const next=C.clone(state()),old=next.settings.members[index],n=name.trim();if(!n||n==='all'||n===C.UNKNOWN||next.settings.members.some((m,i)=>i!==index&&m===n)){toast('重複しない名義名を入力してください。');render();return;}next.settings.members[index]=n;for(const r of [...next.holdings,...next.transactions])if(r.owner===old)r.owner=n;for(const [a,o]of Object.entries(next.settings.accountOwners))if(o===old)next.settings.accountOwners[a]=n;if(owner===old)owner=n;update(next);render();}
const actions={demo:()=>{demo=C.sample();owner='all';year=Number(C.today().slice(0,4));storageLabel('デモ · 保存しません');go('dashboard');},'exit-demo':()=>{demo=null;owner='all';storageLabel(live.settings.persist?'端末に保存済み':'今回のみ');go('dashboard');},'add-holding':()=>editHolding(''),'close-modal':closeModal,'export-holdings':exportHoldings,'export-dividends':exportDividends,template,'parse-paste':()=>{try{paste=$('#paste-csv').value;if(demo){demo=null;storageLabel(live.settings.persist?'端末に保存済み':'今回のみ');}queue=[];newDraft(C.parseCSV(paste),'貼り付けデータ');render();}catch(e){toast(e.message);}},'cancel-import':()=>nextFile(),'commit-import':commitImport,'run-forecast':forecastRun,'refresh-consult':()=>{updateConsultInput();render();},'copy-consult':copyConsult,'export-markdown':()=>{updateConsultInput();download(C.markdown(pack()),'ChatGPT資産相談_'+C.today()+'.md','text/markdown;charset=utf-8');},'export-consult-json':()=>{updateConsultInput();download(JSON.stringify(pack(),null,2),'ChatGPT資産相談_'+C.today()+'.json','application/json');},backup:backupModal,'backup-plain':plainBackup,'backup-encrypted':encryptBackup,restore:()=>$('#restore-file').click(),'decrypt-restore':decryptRestore,'add-member':()=>showModal('<h2>名義を追加</h2>'+field('表示する名義名','new-member','','text','maxlength="40"')+'<div class="modal-actions"><button class="button" data-action="close-modal">キャンセル</button><button class="button primary" data-action="save-member">追加</button></div>'),'save-member':()=>{const name=$('#new-member').value.trim();if(!name||name==='all'||name===C.UNKNOWN||allOwners().includes(name)){toast('重複しない名義名を入力してください。');return;}const n=C.clone(state());n.settings.members.push(name);update(n);closeModal();render();},'save-tax':()=>{const rate=C.num($('#tax-rate').value);if(rate===null||rate<0||rate>100){toast('0〜100%で設定してください。');return;}const n=C.clone(state());n.settings.taxRate=rate;update(n);render();toast('予測用の税率を保存しました。');},clear:async()=>{if(!confirm('保有資産・入出金・名義設定・保存済みデータをすべて削除します。必要なバックアップは保存しましたか？'))return;if(demo){demo=null;storageLabel(live.settings.persist?'端末に保存済み':'今回のみ');go('dashboard');return;}live=C.empty();owner='all';draft=null;queue=[];await saveQueue;try{await db('delete');storageLabel('今回のみ');go('dashboard');toast('実データを削除しました。');}catch(e){toast('端末内データの削除に失敗しました：'+e.message);}}};
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;try{if(b.dataset.view)go(b.dataset.view);else if(b.dataset.go)go(b.dataset.go);else if(b.dataset.action&&actions[b.dataset.action]){const p=actions[b.dataset.action]();if(p?.catch)p.catch(err=>toast(err.message));}else if(b.hasAttribute('data-edit-h'))editHolding(b.dataset.editH);else if(b.hasAttribute('data-save-h'))saveHolding(b.dataset.saveH);else if(b.hasAttribute('data-delete-h')){if(confirm('この保有資産を削除しますか？')){const n=C.clone(state());n.holdings=n.holdings.filter(h=>h.id!==b.dataset.deleteH);update(n);closeModal();render();}}else if(b.dataset.editT)editTransaction(b.dataset.editT);else if(b.dataset.saveT)saveTransaction(b.dataset.saveT);else if(b.dataset.txfilter){txFilter=b.dataset.txfilter;page=0;render();}else if(b.dataset.page){page=Math.max(0,page+Number(b.dataset.page));render();}}catch(err){toast('操作できませんでした：'+err.message);console.error(err);}});
document.addEventListener('change',e=>{const t=e.target;try{if(t.id==='owner-filter'){owner=t.value;page=0;render();}else if(t.id==='year-filter'){year=Number(t.value);page=0;render();}else if(t.id==='encoding')encoding=t.value;else if(t.id==='import-files')startFiles(t.files);else if(t.id==='restore-file')restoreFile(t.files[0]);else if(t.id==='anonymous'){anonymous=t.checked;if($('#question'))question=$('#question').value;render();}else if(t.id==='persist-toggle'){const n=C.clone(state());n.settings.persist=t.checked;update(n);render();}else if(t.dataset.account){const n=C.clone(state());Object.defineProperty(n.settings.accountOwners,t.dataset.account,{value:t.value,enumerable:true,writable:true,configurable:true});update(n);render();}else if(t.hasAttribute('data-member'))renameMember(Number(t.dataset.member),t.value);else if(draft&&(t.id.startsWith('imp-')||t.hasAttribute('data-map'))){if(t.dataset.map)draft.map[t.dataset.map]=Number(t.value);else{const k={'imp-type':'type','imp-owner':'owner','imp-account':'account','imp-asof':'asOf','imp-class':'assetClass','imp-tax':'taxType','imp-mode':'mode'}[t.id];if(k)draft[k]=t.value;if(t.id==='imp-type')draft.map=C.mapping(draft.parsed.headers,draft.type);}render();}}catch(err){toast(err.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;page=0;const caret=e.target.selectionStart;render();const input=$('#search');input?.focus();if(input&&caret!==null)try{input.setSelectionRange(caret,caret);}catch{}}if(e.target.id==='question')question=e.target.value;if(e.target.id==='paste-csv')paste=e.target.value;});
$('#privacy-toggle').onclick=()=>{hideMoney=!hideMoney;document.body.classList.toggle('hide-money',hideMoney);$('#privacy-toggle').setAttribute('aria-label',hideMoney?'金額を表示':'金額を隠す');};$('#exit-demo').onclick=actions['exit-demo'];$('.brand').onclick=e=>{e.preventDefault();go('dashboard');};
(async()=>{try{const stored=await db('get');if(stored){live=C.validateBackup(stored);storageLabel(live.settings.persist?'端末に保存済み':'今回のみ');}}catch(e){toast('保存済みデータを読み込めませんでした。復元用バックアップをご利用ください。');}render();})();
})();
