/* Asset Compass dashboard layout v1.1.0 — restructures the dashboard without touching finance logic. */
(function(){
'use strict';
const main=document.querySelector('#main');
if(!main)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeView=()=>document.querySelector('#nav button.active')?.dataset.view;
function renamePanel(panel,title,sub){if(!panel)return;const h=panel.querySelector('.panel-head h2');if(h)h.textContent=title;const p=panel.querySelector('.panel-head p');if(p&&sub)p.textContent=sub;}
function actionPanel(kind,title,body,buttonText,go,icon){const section=document.createElement('section');section.className='panel dashboard-action-card '+kind;section.innerHTML='<div class="dashboard-action-icon" aria-hidden="true">'+icon+'</div><div class="dashboard-action-copy"><h2>'+esc(title)+'</h2><p>'+esc(body)+'</p></div><button class="button compact dashboard-action-button" data-go="'+esc(go)+'">'+esc(buttonText)+' <span aria-hidden="true">→</span></button>';return section;}
function makeOwnerVisual(panel){if(!panel||panel.querySelector('.owner-visual-v3'))return;const table=panel.querySelector('table');if(!table)return;const rows=[...table.querySelectorAll('tbody tr')];if(!rows.length)return;const visual=document.createElement('div');visual.className='owner-visual-v3';const items=[];for(const row of rows){const cells=[...row.children];if(cells.length<4)continue;const name=cells[0].querySelector('strong')?.textContent?.trim()||cells[0].textContent.trim();const initial=name.slice(0,1)||'・';const value=cells[1].textContent.trim();const actual=cells[2].textContent.trim();const forecast=cells[3].textContent.trim();const width=row.querySelector('.progress-track span')?.style.width||'0%';items.push('<div class="owner-visual-row"><span class="owner-visual-avatar">'+esc(initial)+'</span><div class="owner-visual-main"><div class="owner-visual-top"><strong>'+esc(name)+'</strong><span class="money">'+esc(value)+'</span></div><div class="owner-visual-track"><span style="width:'+esc(width)+'"></span></div><div class="owner-visual-meta"><span>配当実績 '+esc(actual)+'</span><span>年間予測 '+esc(forecast)+'</span></div></div></div>');}if(!items.length)return;visual.innerHTML=items.join('');table.closest('.table-wrap')?.classList.add('dashboard-source-table');panel.appendChild(visual);}
function makeImportHistory(diag){const section=diag||document.createElement('section');section.classList.add('panel','dashboard-history-card');if(diag){section.classList.add('dashboard-diagnostic-live');const h=section.querySelector('.panel-head h2');if(h)h.textContent='最近の取込・診断結果';const p=section.querySelector('.panel-head p');if(p)p.textContent='配当認識・年別集計・除外状況';}else{section.innerHTML='<div class="panel-head"><div><h2>最近の取込・診断結果</h2><p>CSVの取込結果と配当認識を確認</p></div><button class="button ghost compact" data-go="import">取込履歴 →</button></div><div class="dashboard-empty-note"><span class="history-status">✓</span> CSVを取り込むと、ここに認識状況を表示します。</div>';}return section;}
function compactHead(head){if(!head)return;head.classList.add('dashboard-v3-head');const eyebrow=head.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent='ASSET OVERVIEW';const h=head.querySelector('h1');if(h){h.textContent='資産サマリー';h.setAttribute('aria-label','資産の全体像');}const p=head.querySelector('p');if(p)p.textContent='家族の資産状況・配当・予測を一覧で確認できます。';}
function relabelMetrics(metrics){if(!metrics)return;metrics.classList.add('dashboard-v3-metrics');const cards=[...metrics.querySelectorAll('.metric')];const labels=['総資産','受取配当','年間配当予測','含み損益'];cards.forEach((card,i)=>{card.classList.add('dashboard-kpi');const label=card.querySelector('.metric-label');if(label)label.textContent=labels[i]||label.textContent;const icon=['◎','▥','↗','⌁'][i]||'•';if(!card.querySelector('.dashboard-kpi-icon'))card.insertAdjacentHTML('afterbegin','<span class="dashboard-kpi-icon" aria-hidden="true">'+icon+'</span>');});}
function transformEmpty(){if(activeView()!=='dashboard'||main.querySelector('.dashboard-empty-v3'))return;const welcome=main.querySelector(':scope > .welcome');if(!welcome)return;const head=main.querySelector(':scope > .page-head');compactHead(head);const steps=main.querySelector(':scope > .steps');const callout=main.querySelector(':scope > .callout');const wrap=document.createElement('div');wrap.className='dashboard-empty-v3';if(head)wrap.appendChild(head);const hero=document.createElement('section');hero.className='dashboard-empty-hero';hero.innerHTML='<div><span class="dashboard-empty-kicker">ASSET COMPASS</span><h2>CSVを取り込んで、<br>資産と配当をひとつの画面へ。</h2><p>Money Forwardのデータを端末内で整理し、家族別の資産・配当・将来予測につなげます。</p><div class="actions"><button class="button primary" data-go="import">CSVを取り込む</button><button class="button" data-action="demo">サンプルで体験する →</button></div></div><div class="dashboard-empty-orbit" aria-hidden="true">◈</div>';wrap.appendChild(hero);if(steps)wrap.appendChild(steps);if(callout)wrap.appendChild(callout);welcome.remove();main.replaceChildren(wrap);}
function transformDashboard(){if(activeView()!=='dashboard')return;if(main.querySelector(':scope > .dashboard-v3')){const diag=main.querySelector('#income-diagnostic');if(diag&&!diag.classList.contains('dashboard-diagnostic-live')){const old=main.querySelector('.dashboard-history-card');const fresh=makeImportHistory(diag);if(old&&old!==fresh)old.replaceWith(fresh);}return;}if(main.querySelector(':scope > .welcome')){transformEmpty();return;}const head=main.querySelector(':scope > .page-head');const metrics=main.querySelector(':scope > .metrics');const gridTwo=main.querySelector(':scope > .grid-two');const gridEqual=main.querySelector(':scope > .grid-equal');const ownerPanel=[...main.querySelectorAll(':scope > .panel')].find(p=>p.querySelector('.panel-head h2')?.textContent.includes('名義別'));const diag=main.querySelector('#income-diagnostic');const warning=[...main.querySelectorAll(':scope > .callout.warning')].find(x=>x!==diag);if(!head||!metrics||!gridTwo||!ownerPanel||!gridEqual)return;const topPanels=[...gridTwo.children].filter(x=>x.classList.contains('panel'));const bottomPanels=[...gridEqual.children].filter(x=>x.classList.contains('panel'));const trend=topPanels[0],allocation=topPanels[1],monthly=bottomPanels[0];compactHead(head);relabelMetrics(metrics);renamePanel(ownerPanel,'名義別内訳','家族ごとの登録資産・配当を比較');makeOwnerVisual(ownerPanel);renamePanel(allocation,'資産配分（アセットアロケーション）','保有資産CSVの評価額ベース');renamePanel(monthly,'配当トラッカー',yearLabel()+'の月別受取実績と年間予測');renamePanel(trend,'資産推移','家族全体の資産残高の変化');const wrap=document.createElement('div');wrap.className='dashboard-v3';wrap.appendChild(head);wrap.appendChild(metrics);const meSummary=main.querySelector('#me-summary');if(meSummary)wrap.appendChild(meSummary);if(warning)wrap.appendChild(warning);const row1=document.createElement('div');row1.className='dashboard-v3-grid dashboard-v3-main';row1.appendChild(ownerPanel);if(allocation)row1.appendChild(allocation);wrap.appendChild(row1);const row2=document.createElement('div');row2.className='dashboard-v3-grid dashboard-v3-secondary';if(monthly)row2.appendChild(monthly);if(trend)row2.appendChild(trend);wrap.appendChild(row2);const row3=document.createElement('div');row3.className='dashboard-v3-bottom';row3.appendChild(actionPanel('import-card','CSVインポート','Money ForwardのCSVを読み込み、資産・配当を更新します。','CSVを取り込む','import','⇧'));row3.appendChild(makeImportHistory(diag));row3.appendChild(actionPanel('consult-card','ChatGPT出力','資産・配当・予測の前提を整理して、相談用データを作成します。','相談データを作る','consult','✧'));wrap.appendChild(row3);for(const p of bottomPanels.slice(1))p.remove();gridTwo.remove();gridEqual.remove();main.replaceChildren(wrap);}
function yearLabel(){return document.querySelector('#year-filter')?.selectedOptions?.[0]?.textContent||'選択年';}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{queued=false;transformDashboard();}));}
new MutationObserver(schedule).observe(main,{childList:true,subtree:false});document.addEventListener('change',e=>{if(e.target?.id==='year-filter'||e.target?.id==='owner-filter')schedule();});const version=document.querySelector('.sidebar-bottom small');if(version)version.textContent='非公式補助アプリ · v1.1.0';schedule();
})();
