const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const C=require('../dividends-core.js');
const receipt=(extra={})=>C.normalizeReceipt({date:'2025-06-20',symbol:'1234.T',name:'検証銘柄',owner:'OTS',broker:'SBI',accountType:'specific',currency:'JPY',gross:1000,tax:200,net:800,...extra});
test('missing dividends remain null, explicit zero stays zero',()=>{assert.equal(C.total([null,undefined,NaN]).value,null);assert.equal(C.total([null,0]).value,0);assert.deepEqual(C.total([0,10,null]),{value:10,known:2,missing:1});});
test('history contains ten completed periods only and never adds forecasts',()=>{const years=Array.from({length:12},(_,i)=>({period:`${2015+i}-03`,annual:i}));const h=C.history({years,forecast:{period:'2027-03',annual:999}});assert.equal(h.length,10);assert.equal(h[0].period,'2017-03');assert.equal(h.at(-1).annual,11);assert.equal(C.stats(h).value,65);});
test('ten observations mean nine annual growth intervals, not ten',()=>{const r=Array.from({length:10},(_,i)=>({period:`${2016+i}-03`,annual:100*1.1**i}));assert.ok(Math.abs(C.stats(r).growth-10)<1e-8);assert.equal(C.stats(r).span,9);assert.equal(C.stats([{period:'2024-03',annual:0},{period:'2025-03',annual:10}]).growth,null);});
test('changed fiscal month is not described as annual dividend growth',()=>{assert.equal(C.trend({period:'2025-09',annual:50},{period:'2025-03',annual:100}),'期の長さを確認');assert.equal(C.trend({period:'2025-03',annual:0},{period:'2024-03',annual:100}),'無配へ');});
test('unknown tax does not manufacture net income even for NISA',()=>{const r=receipt({accountType:'nisa',tax:null,net:null});assert.equal(r.tax,null);assert.equal(r.net,null);assert.equal(r.gross,1000);});
test('calculate only amounts supported by two entered amounts',()=>{assert.equal(receipt({net:null}).net,800);assert.equal(receipt({tax:null}).tax,200);assert.equal(receipt({gross:null}).gross,1000);assert.throws(()=>receipt({net:999}),/一致/);assert.throws(()=>receipt({tax:1001,net:null}),/確認/);});
test('old NISA and junior NISA remain separate and independent of holdings',()=>{assert.equal(receipt({accountType:'旧NISA'}).accountType,'oldNisa');assert.equal(receipt({accountType:'ジュニアNISA'}).accountType,'juniorNisa');assert.equal(receipt({accountType:'特定口座'}).accountType,'specific');});
test('receipt years are exactly ten, currencies and account filters do not mix',()=>{const list=[receipt({date:'2016-06-20'}),receipt(),receipt({owner:'OKS'}),receipt({currency:'USD'})];const a=C.annualReceipts(list,2025,'net',{currency:'JPY',owner:'OTS'});assert.equal(a.length,10);assert.equal(a[0].year,2016);assert.equal(a[0].value,800);assert.equal(a[1].value,null);assert.equal(a[9].value,800);});
test('partial yearly records are visibly incomplete',()=>{const a=C.annualReceipts([receipt(),receipt({tax:null,net:null})],2025,'net',{currency:'JPY'}).at(-1);assert.equal(a.value,800);assert.equal(a.missing,1);assert.equal(a.count,2);});
test('CSV supports BOM, commas and multiline notes; unknown columns cannot become receipts',()=>{const csv='\uFEFF受取日,銘柄コード,税引前,税額,税引後,備考\r\n2025/6/20,1234,"1,000",200,800,"一行\n二行"';const a=C.parseInput(csv,'2026-09-16');assert.equal(a[0].symbol,'1234.T');assert.equal(a[0].gross,1000);assert.equal(a[0].note,'一行\n二行');assert.throws(()=>C.parseInput('{"holdings":[]}','2026-09-16'),/receipts/);});
test('CSV/JSON round-trip and identical reimport is skipped',()=>{const r=receipt();assert.deepEqual(C.parseInput(C.toCSV([r])),[r]);const m=C.merge([r],[r]);assert.equal(m.added,0);assert.equal(m.skipped,1);});
test('explicit ids distinguish otherwise identical deposits and conflicts stop the import',()=>{const r=receipt({id:'a'});assert.equal(C.merge([r],[receipt({id:'b'})]).added,1);assert.throws(()=>C.merge([r],[receipt({id:'a',gross:2000,net:1800})]),/異なります/);});
test('invalid dates, future receipts, empty values and malformed CSV are rejected',()=>{assert.throws(()=>receipt({date:'2025-02-29'}),/存在しない/);assert.equal(receipt({date:'2024-02-29'}).date,'2024-02-29');assert.throws(()=>C.parseInput(JSON.stringify([receipt({date:'2030-01-01'})]),'2026-09-16'),/未来/);assert.throws(()=>receipt({gross:'',net:'',tax:''}),/必要/);assert.throws(()=>C.parseCSV('date,net\n"2025-01-01,10'),/閉じ/);});
test('CSV escapes spreadsheet formulas in user text',()=>{assert.match(C.toCSV([receipt({note:'=1+1'})]),/"'=1\+1"/);});
test('public parser uses the adjusted column, does not add raw quarters across a split',()=>{
const py=String.raw`import importlib.util
s=importlib.util.spec_from_file_location('div','scripts/fetch-dividends.py'); m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
p='''<title>検証会社【1234】：配当</title><table><tr><th>日付</th><th>年間配当（調整後）</th><th>年間配当（調整前）</th></tr><tr><td>2027年3月期</td><td>予想</td><td>99</td><td>---</td><td>10</td><td>---</td><td>89</td><td>99</td></tr><tr><td>実績</td><td>---</td><td>---</td><td>---</td><td>---</td><td>---</td><td>---</td></tr></table><table><tr><th>日付</th><th>年間配当（調整後）</th><th>年間配当（調整前）</th></tr><tr><td>2026年3月期</td><td>13.67</td><td>---</td><td>20</td><td>---</td><td>7</td><td>---</td></tr><tr><td>2025年3月期</td><td>0.00</td><td>---</td><td>0</td><td>---</td><td>0</td><td>0</td></tr><tr><td>2024年3月期</td><td>---</td><td>---</td><td>---</td><td>---</td><td>---</td><td>---</td></tr></table><table><tr><th>日付</th><th>配当性向</th><th>EPS（調整後）</th></tr><tr><td>2026年3月期</td><td>55</td><td>999</td></tr></table>'''
r=m.parse(p,'1234.T','2026-09-16');assert len(r['years'])==3;assert r['years'][0]['annual'] is None;assert r['years'][1]['annual']==0;assert r['years'][2]['annual']==13.67;assert r['years'][2]['unadjustedAnnual'] is None;assert r['forecast']['annual']==99
print('parser OK')`;
 assert.match(execFileSync('python3',['-c',py],{cwd:require('node:path').join(__dirname,'..'),encoding:'utf8'}),/parser OK/);
});
test('receipt data never goes in network parameters; public fetch remains same-origin',()=>{const s=fs.readFileSync(require('node:path').join(__dirname,'..','dividends.js'),'utf8');assert.match(s,/fetch\('\.\/dividends-data\.json\?ts='/);assert.doesNotMatch(s,/fetch\([^\n]*(?:owner|gross|net|shares)/);});
