'use strict';
const assert=require('node:assert/strict'),test=require('node:test'),C=require('../../household-ledger/core.js');
const h='計算対象,日付,内容,金額（円）,保有金融機関,大項目,中項目,メモ,振替,ID';
const tx=(x={})=>C.restore({date:'2026-08-25',amt:-1000,desc:'お店',acc:'A',maj:'食費',sub:'外食',include:1,xfer:0,id:'one',src:'Money Forward',...x});
test('CSV quoted newline, comma, quote and BOM',()=>{let a=C.csv('\uFEFFa,b\r\n"multi\nline","x,""y"""');assert.deepEqual(a,[['a','b'],['multi\nline','x,"y"']]);});
test('Malformed quote rejected',()=>assert.throws(()=>C.csv('a,b\n"open,3')));
test('Invalid dates rejected',()=>{assert.equal(C.date('2026/02/30'),'');assert.equal(C.date('2024/2/29'),'2024-02-29');assert.equal(C.date('2026/13/01'),'');});
test('Malformed amount not changed to zero',()=>assert.throws(()=>C.number('不明')));
test('MF import preserves signed refunds and flags',()=>{let a=C.parse(h+'\n0,2026/08/25,返金,100,A,食費,食料品,,1,x','x');assert.equal(a[0].amt,100);assert.equal(a[0].include,0);assert.equal(a[0].xfer,1);assert.equal(C.total(a).expense,-100);});
test('Money direction follows category; negative income reduces income',()=>{assert.deepEqual(C.total([tx({amt:500}),tx({amt:-100,maj:'収入',kind:'income'})]),{income:-100,expense:-500,balance:400,n:2});});
test('Kakeibon negative expense preserved as positive refund',()=>{let a=C.parse('日付,方法,収入,支出,カテゴリ,品目,集計の設定\n2012-05-16,payment,0,-900,その他,振替 SBI,集計に含めない','old');assert.equal(a[0].amt,900);assert.equal(a[0].include,0);});
test('Different IDs or accounts are not exact duplicates',()=>{let a=C.dedup([tx(),tx({id:'two'}),tx({acc:'B'})]);assert.equal(a.filter(x=>x.dup==='exact').length,0);assert.equal(C.total(a.filter(C.active)).expense,3000);});
test('Identical ID duplicate excluded but original flags unchanged',()=>{let a=C.dedup([tx(),tx()]);assert.equal(a[1].dup,'exact');assert.equal(a[1].include,1);assert.equal(C.total(a.filter(C.active)).expense,1000);});
test('Same ID conflicting categories retained for review',()=>{let a=C.dedup([tx(),tx({maj:'日用品'})]);assert.equal(a[1].dup,'conflict');assert.equal(C.total(a.filter(C.active)).expense,2000);});
test('ID-less identical rows not automatically excluded',()=>{let a=C.dedup([tx({id:''}),tx({id:''})]);assert.equal(a[1].dup,'candidate');assert.equal(a.filter(C.active).length,2);});
test('Conflicts in overrides prevent silent discard',()=>{let a=C.dedup([tx(),tx({merchantOverride:'別の店'})]);assert.equal(a[1].dup,'conflict');});
test('Restored bogus legacy dup is recomputed',()=>{assert.equal(C.dedup([tx({dup:'exact'})])[0].dup,'');});
test('Transfers, excluded rows and balances not counted',()=>{assert.equal([tx({include:0}),tx({xfer:1}),tx({kind:'balance'})].filter(C.active).length,0);});
test('Consecutive periods preserve missing months and years',()=>{let a=C.periods([tx({date:'2019-12-01'}),tx({date:'2020-02-01'})]);assert.deepEqual(a,['2019-12','2020-01','2020-02']);assert.equal(C.move('2019-12',1),'2020-01');assert.equal(C.move('2020-01',-1),'2019-12');assert.equal(C.move('2019-09',1,'year'),'2020-09');});
test('2026 holidays match published Cabinet Office list',()=>{let expected=['01-01','01-12','02-11','02-23','03-20','04-29','05-03','05-04','05-05','05-06','07-20','08-11','09-21','09-22','09-23','10-12','11-03','11-23'].map(x=>'2026-'+x);assert.deepEqual([...C.holidays(2026)].sort(),expected.sort());});
test('2019 accession and 2020-2021 Olympic exceptions',()=>{for(let d of ['2019-04-30','2019-05-01','2019-05-02','2019-10-22','2020-07-23','2020-07-24','2021-08-09'])assert(C.holidays(+d.slice(0,4)).has(d));assert(!C.holidays(2020).has('2020-07-20'));});
test('Holiday is separate from Saturday and Sunday',()=>{assert.equal(C.dayType('2026-05-03'),'祝日・振替休日');assert.equal(C.dayType('2026-08-22'),'土曜日（祝日以外）');assert.equal(C.dayType('2026-08-23'),'日曜日（祝日以外）');assert.equal(C.dayType('2028-08-21'),'平日（祝日未確認）');});
test('Salary paydays weekend and holiday adjustment',()=>{assert.equal(C.payday('2019-01-01',20),'2019-01-18');assert.equal(C.payday('2019-10-01',20),'2019-10-18');assert.equal(C.payday('2026-07-01',20),'2026-07-17');});
test('Salary only salary-related income off payday is candidate',()=>{assert.equal(C.salary(tx({date:'2019-01-18',amt:300000,maj:'収入',sub:'給与'})).key,'通常給与');assert.equal(C.salary(tx({date:'2019-12-05',amt:500000,maj:'収入',sub:'給与'})).key,'賞与候補（日付）');assert.equal(C.salary(tx({amt:500000,maj:'収入',sub:'賞与'})).key,'賞与（指定・記録）');assert.equal(C.salary(tx({date:'2026-08-25',amt:300000,maj:'収入',sub:'給与'})).key,'通常給与');});
test('Rakuma and reimbursement not salary',()=>{for(let desc of ['ラクマ 振込','立替金精算'])assert.equal(C.salary(tx({amt:10000,maj:'収入',sub:'給与',desc})).key,'対象外');});
test('Salary override reversible without changing original fields',()=>{let t=tx({amt:120000,maj:'収入',sub:'給与',salaryOverride:'bonus'});assert.equal(C.salary(t).key,'賞与（指定・記録）');assert.equal(t.sub,'給与');});
test('Food excludes recharge, separates drinking party, prioritizes grocery delivery',()=>{assert.equal(C.food(tx({desc:'WAONチャージ'})),'チャージ等（別枠）');assert.equal(C.food(tx({sub:'飲み会'})),'飲み会（別枠）');assert.equal(C.food(tx({desc:'パルシステム宅配利用代',sub:'夜ご飯'})),'食料品');});
test('Merchant alias and usage-days count not yen or visits',()=>{let a=[tx({date:'2026-08-01',desc:'PayPay びっくりドンキー北店'}),tx({date:'2026-08-01',desc:'びっくりドンキー南店'})],g=C.group(a,t=>C.merchant(t));assert.equal(g[0].key,'びっくりドンキー');assert.equal(g[0].count,2);assert.equal(g[0].days,1);assert.equal(g[0].amount,2000);});
test('Education breakdown',()=>{assert.equal(C.education(tx({maj:'教養・教育',sub:'塾'})),'塾');assert.equal(C.education(tx({maj:'教養・教育',desc:'PAYPAL *QQE'})),'英語学習');});
test('CSV round trip protected text, overrides, source and amounts',()=>{let rows=C.dedup([tx({desc:'=1+1',memo:'@x',amt:-999,merchantOverride:'店舗X'}),tx({id:'income',maj:'収入',amt:-3,desc:'+危険'})]),r=C.parse(C.exportCSV(rows),'export');for(let i=0;i<rows.length;i++)for(let k of ['desc','memo','amt','include','xfer','id','src','kind','merchantOverride'])assert.equal(r[i][k],rows[i][k]);});
test('Strict import atomic validation catches invalid date',()=>assert.throws(()=>C.parse(h+'\n1,2026/02/30,X,-2,A,食費,外食,,0,1','bad')));
