/* Household Compass 0.4. Local-only, lossless records and conservative analysis. */
(function(root){'use strict';
const text=v=>String(v??''),norm=v=>text(v).normalize('NFKC').toLowerCase().replace(/[\s・･]/g,''),pad=n=>String(n).padStart(2,'0');
const iso=d=>d.toISOString().slice(0,10),dt=s=>new Date(s+'T00:00:00Z');
function date(v){const m=text(v).trim().match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/);if(!m)return '';const s=`${m[1]}-${pad(m[2])}-${pad(m[3])}`;return +m[1]>=1900&&+m[1]<=2100&&Number.isFinite(+dt(s))&&iso(dt(s))===s?s:'';}
function number(v){let s=text(v).trim().replace(/[¥￥,\s]/g,'');if(s==='')return 0;if(!/^[+-]?\d+(\.\d+)?$/.test(s)||!Number.isSafeInteger(+s))throw Error('金額は整数の円で入力してください: '+text(v).slice(0,35));return +s;}
function csv(str){let rows=[],row=[],cell='',q=false;str=text(str).replace(/^\uFEFF/,'');for(let i=0;i<str.length;i++){const c=str[i];if(q){if(c==='"'&&str[i+1]==='"'){cell+='"';i++;}else if(c==='"')q=false;else cell+=c;}else if(c==='"'&&cell==='')q=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'||c==='\r'){if(c==='\r'&&str[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(q)throw Error('CSVの引用符が閉じていません');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
const HEAD=['計算対象','日付','内容','金額（円）','保有金融機関','大項目','中項目','メモ','振替','ID'];
const incomeCategories=new Set(['収入','給与','給料','給与所得','賞与','臨時収入','年金','副収入','事業所得','配当所得']);
const cmap={'日用雑貨':'日用品','住まい':'住宅','水道・光熱':'水道・光熱費','通信':'通信費','クルマ':'自動車','交通':'交通費','美容・衣服':'衣服・美容','教育・教養':'教養・教育','エンタメ':'趣味・娯楽','税金':'税・社会保障','医療・保険':'健康・医療'};
function parse(str,file){let rows=csv(str);if(rows.length<2)throw Error('明細がありません');let h=rows.shift().map(x=>x.trim()),mf=HEAD.every(x=>h.includes(x)),kk=['日付','方法','収入','支出','カテゴリ'].every(x=>h.includes(x));if(!mf&&!kk)throw Error('対応CSVではありません。家計コンパス、ME、Kakeibon/Zaim形式を選んでください');return rows.map((r,i)=>{if(r.length!==h.length)throw Error(`${file} ${i+2}行: 列数が一致しません`);let o=Object.fromEntries(h.map((k,j)=>[k,r[j]]));if(o['テキスト保護']==='1')for(let k of h)if(/^'[=+\-@\t\r]/.test(o[k]))o[k]=o[k].slice(1);const d=date(o['日付']);if(!d)throw Error(`${file} ${i+2}行: 日付が不正です`);let t;if(mf){if(!['0','1'].includes(o['計算対象'])||!['0','1'].includes(o['振替']))throw Error(`${file} ${i+2}行: 計算対象・振替は0/1です`);let memo=o['メモ']||'';t={date:d,amt:number(o['金額（円）']),include:+o['計算対象'],xfer:+o['振替'],desc:o['内容'],acc:o['保有金融機関']||'口座不明',maj:o['大項目']||'未分類',sub:o['中項目']||'未分類',memo,id:o['ID'],src:o['移行元']||(/KKB-|Kakeibon|旧家計簿/.test(o['ID']+' '+o['保有金融機関']+' '+memo)?'Kakeibon':'Money Forward'),file:o['移行元ファイル']||file,row:o['元行']||i+2,kind:o['記録種別']||(h.includes('移行元')&&!h.includes('記録種別')?(number(o['金額（円）'])>=0?'income':'expense'):(incomeCategories.has(o['大項目'])||(!o['大項目']||o['大項目']==='未分類')&&number(o['金額（円）'])>0?'income':'expense')),salaryOverride:o['給与区分補正']||'',merchantOverride:o['店舗名補正']||''};}else{if(o['通貨']&&o['通貨']!=='JPY')throw Error(`${file} ${i+2}行: 円以外の通貨は未対応です`);let inc=number(o['収入']),exp=number(o['支出']),kind=/balance|残高/.test(o['方法'])?'balance':/transfer|振替/.test(o['方法'])?'transfer':o['方法']==='income'?'income':'expense';let maj=o['カテゴリ']||'未分類';t={date:d,amt:kind==='balance'?number(o['残高調整']):inc-exp,include:/含めない/.test(o['集計の設定'])?0:1,xfer:kind==='transfer'?1:0,desc:o['品目']||o['お店']||'明細',acc:[o['支払元'],o['入金先']].find(x=>x&&x!=='-')||'旧家計簿（口座不明）',maj:kind==='income'?'収入':cmap[maj]||(maj==='-'?'未分類':maj),sub:kind==='income'?maj:(o['カテゴリの内訳']==='-'?'未分類':o['カテゴリの内訳']||'未分類'),memo:[o['メモ'],o['お店']&&'元店名='+o['お店'],'旧分類='+maj+'/'+o['カテゴリの内訳']].filter(Boolean).join(' | '),id:'',src:'Kakeibon',file,row:i+2,kind};}return restore(t);});}
function restore(t){if(!t||!date(t.date)||!Number.isSafeInteger(t.amt))throw Error('保存明細の形式を確認してください');return {...t,include:t.include===0?0:1,xfer:t.xfer===1?1:0,desc:text(t.desc),acc:text(t.acc||'口座不明'),maj:text(t.maj||'未分類'),sub:text(t.sub||'未分類'),memo:text(t.memo),id:text(t.id),src:text(t.src||'旧保存データ'),file:text(t.file),row:t.row||'',kind:['balance','transfer','income','expense'].includes(t.kind)?t.kind:t.amt>=0?'income':'expense',salaryOverride:['salary','bonus','other'].includes(t.salaryOverride)?t.salaryOverride:'',merchantOverride:text(t.merchantOverride||'')};}
function dedup(rows){let ids=new Map(),finger=new Map();return rows.map((t,i)=>{t={...t,dup:'',uid:i};let key=t.id?JSON.stringify([t.src,t.acc,t.id]):'',sig=JSON.stringify([t.date,t.amt,t.desc,t.maj,t.sub,t.include,t.xfer,t.memo,t.kind,t.salaryOverride,t.merchantOverride]);if(key){let variants=ids.get(key);if(variants)t.dup=variants.has(sig)?'exact':'conflict';else{variants=new Set();ids.set(key,variants);}variants.add(sig);}let fp=JSON.stringify([t.date,t.amt,norm(t.desc),t.acc]);if(!t.dup&&finger.has(fp))t.dup='candidate';finger.set(fp,true);return t;});}
function active(t){return t.include===1&&!t.xfer&&t.kind!=='balance'&&t.kind!=='transfer'&&t.dup!=='exact';}
function total(rows){let income=0,expense=0;for(const t of rows){if(t.kind==='balance'||t.kind==='transfer')continue;if(t.kind==='income')income+=t.amt;else expense-=t.amt;}return{income,expense,balance:income-expense,n:rows.length};}
const expense=t=>t.kind==='expense'?-t.amt:0;
function move(anchor,n,gran='month'){let [y,m]=anchor.split('-').map(Number);return gran==='year'?`${y+n}-${pad(m)}`:iso(new Date(Date.UTC(y,m-1+n,1))).slice(0,7);}
const inPeriod=(t,a,g)=>t.date.startsWith(g==='year'?a.slice(0,4):a);
function periods(rows){if(!rows.length)return [];let s=rows.map(t=>t.date.slice(0,7)).sort(),out=[],a=s[0];while(a<=s[s.length-1]&&out.length<2500){out.push(a);a=move(a,1);}return out;}
function group(rows,fn,amount=expense){let m=new Map();for(const t of rows){let k=fn(t);if(!k)continue;let v=m.get(k)||{key:k,amount:0,count:0,days:new Set(),rows:[]};v.amount+=amount(t);v.count++;v.days.add(t.date);v.rows.push(t);m.set(k,v);}return [...m.values()].map(v=>({...v,days:v.days.size})).sort((a,b)=>b.amount-a.amount||a.key.localeCompare(b.key));}
// Calendar rules for 2010–2027, based on Cabinet Office holiday rules (2026-09-23).
const holidayCache=new Map();function holidays(y){if(y<2010||y>2027)return new Set();if(holidayCache.has(y))return holidayCache.get(y);let s=new Set(),add=(m,d)=>s.add(`${y}-${pad(m)}-${pad(d)}`),mon=(m,n)=>1+(8-new Date(Date.UTC(y,m-1,1)).getUTCDay())%7+7*(n-1);[[1,1],[2,11],[4,29],[5,3],[5,4],[5,5],[11,3],[11,23]].forEach(x=>add(...x));add(1,mon(1,2));add(9,mon(9,3));add(3,Math.floor(20.8431+.242194*(y-1980)-Math.floor((y-1980)/4)));add(9,Math.floor(23.2488+.242194*(y-1980)-Math.floor((y-1980)/4)));if(y<=2018)add(12,23);if(y>=2020)add(2,23);if(y===2020){add(7,23);add(7,24);add(8,10);}else if(y===2021){add(7,22);add(7,23);add(8,8);}else{add(7,mon(7,3));add(10,mon(10,2));if(y>=2016)add(8,11);}if(y===2019){add(5,1);add(10,22);}for(let d=new Date(Date.UTC(y,0,2));d.getUTCFullYear()===y;d.setUTCDate(d.getUTCDate()+1)){let prev=iso(new Date(+d-864e5)),next=iso(new Date(+d+864e5));if(s.has(prev)&&s.has(next))s.add(iso(d));}for(let day of [...s])if(dt(day).getUTCDay()===0){let d=dt(day);do{d.setUTCDate(d.getUTCDate()+1);}while(s.has(iso(d)));s.add(iso(d));}holidayCache.set(y,s);return s;}
function dayType(date){let y=+date.slice(0,4),w=dt(date).getUTCDay();if(holidays(y).has(date))return'祝日・振替休日';return w===6?'土曜日（祝日以外）':w===0?'日曜日（祝日以外）':y<2010||y>2027?'平日（祝日未確認）':'通常平日';}
function payday(date,day){let [y,m]=date.split('-').map(Number),d=new Date(Date.UTC(y,m-1,day));while([0,6].includes(d.getUTCDay())||holidays(y).has(iso(d))||(d.getUTCMonth()===0&&d.getUTCDate()<=3))d.setUTCDate(d.getUTCDate()-1);return iso(d);}
function salary(t,opt={}){if(t.salaryOverride==='other')return{key:'対象外',reason:'手動指定'};if(t.salaryOverride)return{key:t.salaryOverride==='salary'?'通常給与':'賞与（指定・記録）',reason:'手動指定'};let body=norm(t.desc+' '+t.memo),cat=norm(t.maj+' '+t.sub);if(t.kind!=='income'||/ラクマ|フリマ|メルカリ|立替|精算|配当|給付|手当還付/.test(body+' '+cat))return{key:'対象外',reason:'給与以外'};if(/賞与|ボーナス|ショウヨ|シヨウヨ/.test(norm(t.desc+' '+t.maj+' '+t.sub))||/給与種別=賞与/.test(t.memo))return{key:'賞与（指定・記録）',reason:'明細または元分類に賞与の記載'};if(!/給与|給料|キユウヨ|キュウヨ/.test(body+' '+cat))return{key:'対象外',reason:'給与の根拠なし'};let day=+t.date.slice(0,4)<=2019?(opt.legacyDay||20):(opt.currentDay||25),expected=payday(t.date,day);return{key:t.date===expected?'通常給与':'賞与候補（日付）',reason:`基準日${day}日 → ${expected}（土日祝前倒し）。日付だけの推定`};}
function movement(t){let s=norm(t.desc);return t.xfer||t.kind==='transfer'||t.kind==='balance'||/チャージ|ハイブリッド預金|カード引き落とし|カード引落|資金移動/.test(s)||t.sub==='カード引き落とし';}
function food(t){if(t.kind!=='expense')return '';let s=norm(t.desc+' '+t.sub+' '+t.memo);if(movement(t))return 'チャージ等（別枠）';if(/飲み会|宴会|忘年会|新年会|歓送迎/.test(s))return '飲み会（別枠）';if(t.maj!=='食費')return '';if(/パルシステム|生協宅配|食料品/.test(s))return '食料品';if(/カフェ|喫茶/.test(s))return 'カフェ';if(/デザート|スイーツ|お菓子/.test(s))return '菓子・スイーツ';if(/飲み物|自販機/.test(s))return '飲み物';if(/外食|朝ご飯|昼ご飯|夜ご飯|朝食|昼食|夕食|レストラン|びっくりドンキー|マクドナルド|丸亀|吉野家|ガスト|くら寿司|スシロー/.test(s))return '外食・食事';return '食費（内訳未確認）';}
function education(t){if(t.kind!=='expense'||t.maj!=='教養・教育')return '';let s=norm(t.desc+' '+t.sub);if(/塾|コベツジユク/.test(s))return '塾';if(/qqe|英語|英会話/.test(s))return '英語学習';if(/書籍|教材|本/.test(s))return '書籍・教材';if(/学費|学校|ガツコウ|給食/.test(s))return '学費・給食';if(/習い|クモン|ベネツセ/.test(s))return '習いごと';return 'その他教育';}
const chains=[['びっくりドンキー',/びっくりドンキー|bd鷺沼/],['丸亀製麺',/丸亀製麺/],['マクドナルド',/マクドナルド/],['ガスト',/ガスト/],['ココス',/coco.s|ココス/],['くら寿司',/くら寿司/],['スシロー',/スシロー/],['ヨークフーズ',/ヨークフーズ/],['マルエツ',/マルエツ/],['東急ストア',/東急ストア/],['そうてつローゼン',/そうてつローゼン/],['イオン',/イオン(横浜|スタイル|モール|御経塚)|^支払御経塚/],['パルシステム',/パルシステム/],['セブン-イレブン',/セブン.イレブン/],['ファミリーマート',/ファミリーマート|フアミリ.?マ.?ト/],['ローソン',/ローソン/],['吉野家',/吉野家/]];
function merchant(t,chain=true){if(t.merchantOverride)return t.merchantOverride;let d=t.desc.normalize('NFKC').replace(/^(＜未確定＞|<未確定>|PayPay\s*|楽天SP\s*|d払い[AB]?\/|支払\s*)/gi,'').replace(/\/NFC$|\s+\d{6}$/g,'').trim();if(chain){let s=norm(d+' '+t.memo);for(let [name,re]of chains)if(re.test(s))return name;}if(/^(朝ご飯|昼ご飯|夜ご飯|食料品|食事|物販)$/.test(d)){let m=t.memo.match(/(?:元店名|元メモ)=([^|]+)/);if(m&&!/^(朝ご飯|昼ご飯|夜ご飯|食料品|物販)$/.test(m[1].trim()))return m[1].trim();return d+'（店名不明）';}return d||'店名不明';}
function exportCSV(rows){let head=[...HEAD,'移行元','移行元ファイル','元行','記録種別','給与区分補正','店舗名補正','重複判定','テキスト保護'];let cell=(v,isNumber=false)=>{v=text(v);if(!isNumber&&/^[=+\-@\t\r]/.test(v))v="'"+v;return /[",\r\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;};let out=rows.map(t=>[t.include,t.date,t.desc,t.amt,t.acc,t.maj,t.sub,t.memo,t.xfer,t.id,t.src,t.file,t.row,t.kind,t.salaryOverride,t.merchantOverride,t.dup,1]);return '\uFEFF'+[head,...out].map((r,i)=>r.map((v,j)=>cell(v,i>0&&[0,3,8,12,17].includes(j))).join(',')).join('\r\n');}
const api={text,norm,pad,date,number,csv,parse,restore,dedup,active,total,expense,move,inPeriod,periods,group,holidays,dayType,payday,salary,movement,food,education,merchant,exportCSV};if(typeof module!=='undefined')module.exports=api;else root.LedgerCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
