"""Dependency-free static build. Generated HTML stays committed for GitHub Pages."""
from pathlib import Path
from html import escape
import json,re
from content import ARTICLES
ROOT=Path(__file__).resolve().parents[1]
BASE='/invest/everyday-japan-lab/'
DATE='2026-09-24'
SOURCES=json.loads((ROOT/'research/sources.json').read_text())
PAGES=[]

def link(slug,text): return f'<a href="{BASE}{slug+"/" if slug else ""}">{text}</a>'
def source_block(keys):
    if not keys:return ''
    rows=''.join(f'<li><a href="{SOURCES[k]["url"]}" rel="noopener">{escape(SOURCES[k]["publisher"])} — {escape(SOURCES[k]["type"])}</a><br>{escape(SOURCES[k]["scope"])}</li>' for k in keys)
    return f'<section class="sources" id="sources"><h2>Sources and scope</h2><p>Primary references checked {DATE}. Manufacturer statements are identified as such.</p><ol>{rows}</ol></section>'

def page(slug,title,deck,body,tag='Everyday Japan Lab',refs=None,tool=False,wide=False):
    refs=refs or []
    description=escape(deck,quote=True)
    nav=''.join(f'<a href="{BASE}{s+"/" if s else ""}"'+(' aria-current="page"' if slug==s else '')+f'>{t}</a>' for s,t in [('','Home'),('topics','Topics'),('tools','Tools'),('about','About')])
    breadcrumb='' if not slug else f'<div class="breadcrumb">{link("","Home")} / {escape(title)}</div>'
    header='' if not slug else f'<header class="page-head">{breadcrumb}<p class="eyebrow">{escape(tag)}</p><h1>{escape(title)}</h1><p class="lede">{escape(deck)}</p><p class="meta">By Everyday Japan Lab · Reviewed {DATE} · Research and planning, not product certification</p></header>'
    fullbody=body+source_block(refs)
    footlinks=''.join(link(s,t) for s,t in [('about','About'),('methodology','Methodology'),('privacy','Privacy'),('contact','Contact'),('advertising','Advertising & affiliate policy'),('sources','Sources')])
    script=f'<script type="module" src="{BASE}assets/tools.mjs"></script>' if tool else ''
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="{description}"><meta name="theme-color" content="#192d36"><title>{escape(title)} | Everyday Japan Lab</title><link rel="stylesheet" href="{BASE}assets/site.css">{script}</head>
<body class="ejl"><a class="skip" href="#main">Skip to content</a><div class="dev-note">Development preview · No advertising · Not indexed for search</div><header class="site-header"><div class="wrap header-inner"><a class="brand" href="{BASE}"><span class="brand-mark" aria-hidden="true">日</span>Everyday Japan Lab</a><nav class="nav" aria-label="Main navigation">{nav}</nav></div></header>
<main class="wrap" id="main">{header}{fullbody}</main>
<footer class="site-footer"><div class="wrap"><div class="footer-top"><div><strong>Everyday Japan Lab</strong><br>Practical systems from everyday Japan.</div><nav class="footer-links" aria-label="Footer">{footlinks}</nav></div><p class="footer-note">Useful ideas need local checks. Product ratings, building conditions and rules vary. We distinguish official guidance, manufacturer claims and our own assumptions. This preview contains no paid placements, affiliate links or analytics tags.</p></div></footer></body></html>'''
    out=ROOT/slug/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(html)
    PAGES.append(dict(slug=slug,title=title,description=deck,tag=tag,body=fullbody,tool=tool))

GUIDES=[('bidet-seats','Bathroom','Will a bidet seat work in your home?','Measure the toilet, check local utilities and understand the limits before buying.'),('heat-pump-water-heaters','Energy','Make sense of heat-pump hot water','Explore Japan’s EcoCute experience and compare a local system against your own demand.'),('emergency-preparedness','Preparedness','Build a reserve you actually use','Plan food, water and sanitation supplies, then subtract what you already have.')]
TOOLS=[('washlet-fit','Bidet seat readiness worksheet','Record measurements and unresolved installation checks.'),('heat-pump-water-heater','Heat-pump water-heater calculator','Compare useful heat, energy input, operating cost and COP scenarios.'),('emergency-stockpile','Emergency stockpile calculator','Count water, meal portions and toilet uses, with a shopping deficit.'),('v2h-backup','V2H backup runtime calculator','Explore an energy budget without assuming vehicle or grid compatibility.'),('parcel-locker','Parcel-locker capacity estimator','See how deliveries, collection delay and chosen headroom affect occupancy.')]
def cards(items):
    return '<div class="grid">'+''.join(f'<article class="card"><span class="tag">{tag}</span><h3>{title}</h3><p>{deck}</p>{link(slug,"Read the guide →")}</article>' for slug,tag,title,deck in items)+'</div>'
def toolcards():
    return '<div class="grid">'+''.join(f'<article class="card"><span class="tag">Free planning tool</span><h3>{title}</h3><p>{deck}</p>{link(slug,"Open tool →")}</article>' for slug,title,deck in TOOLS)+'</div>'

page('','Practical systems from everyday Japan','Evidence-led guides and free planning tools for everyday home decisions.',f'''
<section class="hero"><div><p class="eyebrow">Ideas that earn their place in everyday life</p><h1>From everyday Japan.<br>Useful in your home?</h1><p class="lede">Explore practical systems, understand their trade-offs, and check what would need to work where you live.</p><div class="actions"><a class="button" href="{BASE}topics/">Explore the guides</a><a class="button secondary" href="{BASE}tools/">Use a free tool</a></div><p class="small">No rankings for sale. No universal fit claims. Clear sources and assumptions.</p></div><aside class="hero-aside" aria-label="Our approach"><p class="eyebrow">A useful idea needs context</p><h2>Three questions before you adopt it.</h2><ol class="steps"><li>What problem does it solve?</li><li>What evidence supports it?</li><li>What changes where you live?</li></ol></aside></section>
<section class="section"><div class="section-head"><h2>Start with a real household decision</h2>{link('topics','All published guides →')}</div>{cards(GUIDES)}</section>
<section class="stripe"><h2>Japan is the starting point.<br>Your conditions decide.</h2><p>We study systems used or developed in Japan, then examine their limits abroad. Established products, official recommendations and emerging applications are different kinds of evidence. {link('methodology','Read our method.')}</p></section>
<section class="section"><div class="section-head"><h2>Bring your own numbers</h2>{link('tools','Browse all five tools →')}</div>{toolcards()}</section>''')

topicbody=cards(GUIDES)+'<h2>Go deeper</h2><div class="grid">'
for guide in GUIDES:
    children=[a for a in ARTICLES if a['slug'].startswith(guide[0]+'/')]
    topicbody+=f'<section class="card"><span class="tag">{guide[1]}</span><h3>{guide[2]}</h3>'+''.join(f'<p>{link(a["slug"],escape(a["title"]))}</p>' for a in children)+'</section>'
topicbody+='</div><div class="callout"><p>These are the published guides. Other ideas remain in the research inventory until their evidence and usefulness justify a page.</p></div>'
page('topics','Guides for practical decisions','Three researched starting points, with focused follow-up guides.',topicbody)
page('tools','Free planning tools','Use your own inputs. See the calculation method, check its limits and print the result.',toolcards()+'<div class="callout"><p>Tools run in your browser and do not save your inputs. Example values are editable assumptions, not current prices or typical consumption claims.</p></div>')
for a in ARTICLES:
    siblings=[b for b in ARTICLES if b['slug'].split('/')[0]==a['slug'].split('/')[0] and b!=a]
    aside=f'<aside class="aside"><h2>Put it into practice</h2>{link(a["tool"],"Open the free tool →")}<h2 class="related">Related reading</h2>'+''.join(link(b['slug'],escape(b['title'])) for b in siblings)+'</aside>'
    page(a['slug'],a['title'],a['deck'],f'<div class="article-grid"><article class="prose">{a["body"]}</article>{aside}</div>',a['tag'],a['refs'])

def field(name,label,value,min=0,max=100000,step='any',hint=''):
    return f'<div class="field"><label for="{name}">{label}</label><input id="{name}" name="{name}" type="number" value="{value}" min="{min}" max="{max}" step="{step}" required aria-describedby="{name}-hint"><small id="{name}-hint">{hint}</small></div>'
def select(name,label,options,hint=''):
    return f'<div class="field"><label for="{name}">{label}</label><select id="{name}" name="{name}" aria-describedby="{name}-hint">'+''.join(f'<option value="{v}">{t}</option>' for v,t in options)+f'</select><small id="{name}-hint">{hint}</small></div>'
def fields(legend,*items):return f'<fieldset><legend>{legend}</legend><div class="fields">'+''.join(items)+'</div></fieldset>'
def toolpage(slug,title,deck,model,inputs,method,limits,refs,guide=None):
    form=f'<form class="tool-form" data-tool="{model}" novalidate><p class="small">All fields are required. Starting numbers are examples; change them to match your situation.</p>{inputs}<div class="actions"><button type="submit">Calculate / update</button><button class="secondary" type="reset">Reset examples</button><button class="secondary" type="button" data-print>Print</button></div><p class="error" role="alert" tabindex="-1" hidden></p><section class="result" aria-live="polite" aria-atomic="true" tabindex="-1" hidden></section><noscript><p class="callout">Enable JavaScript to calculate. The method below remains available without JavaScript.</p></noscript></form>'
    aside=f'<aside class="aside"><h2>Before you use the result</h2><p>{limits}</p>'+(link(guide,'Read the full guide →') if guide else '')+'</aside>'
    body=f'<div class="tool-layout">{form}{aside}</div><details open><summary>Formula, assumptions and input limits</summary><div class="prose">{method}</div></details>'
    page(slug,title,deck,body,'Free tool / Transparent assumptions',refs,True)

unknown=[('unknown','Not yet checked'),('yes','Verified for the intended installation'),('no','Not suitable / not present')]
voltage=[('unknown','Unknown'),('100','100 V'),('120','110–120 V class'),('230','220–240 V class')]
toolpage('washlet-fit','Bidet seat readiness worksheet','Record your measurements and the checks still needed before choosing a product.','readiness',
 fields('Toilet measurements',select('unit','Measurement units',[('mm','Millimetres (mm)'),('in','Inches (in)')],'All three measurements use this unit.'),select('shape','Bowl shape',[('unknown','Unknown / other'),('round','Round'),('elongated','Elongated')]),field('length','Bolt centre line to bowl front',480,0.01,1000,hint='Measure from the bolt centre line, not from the tank.'),field('bolts','Bolt spacing, centre to centre',140,0.01,1000),field('clearance','Clearance behind the bolt centre line',60,0,1000,hint='Also photograph the tank/bowl contour.'))+
 fields('Installation information',select('voltage','Local supply voltage class',voltage),select('productVoltage','Chosen product voltage class',voltage),select('outlet','Grounded and protected outlet',unknown,'A qualified local check is needed for location, frequency and circuit rating.'),select('valve','Shut-off valve and water connection',unknown)),
 '<h2>What is compared?</h2><p>The worksheet records dimensions and converts inches to millimetres using 1 in = 25.4 mm. It flags unknown or mismatched voltage classes and unresolved outlet and water connections. It does not contain a product database or universal dimensional pass threshold.</p><p>Physical bounds reject empty, non-finite or implausibly large entries; accepting a number is not evidence of a real fit. Exact voltage and frequency, certification, mounting range, rear contour, hose access and local backflow requirements still need verification.</p>',
 'This is a readiness record, not a compatibility verdict. Compare the exact manufacturer drawing and local installation requirements.', ['TOTO_FIT','BRONDELL_FIT','BRONDELL_MANUAL'],'bidet-seats')

toolpage('heat-pump-water-heater','Heat-pump water-heater cost calculator','Compare a transparent annual-energy scenario against an existing heater.','heatPump',
 fields('Useful hot-water demand',field('litres','Delivered warm water (L/day)',200,0,10000,hint='Mixed water at point of use; not tank volume.'),field('days','Days of use per year',365,1,366,1),field('cold','Cold inlet temperature (°C)',15,0,40),field('hot','Delivered water temperature (°C)',40,1,80,hint='Model input, not a recommended tank setting. Must exceed inlet temperature.'))+
 fields('Performance assumptions',field('cop','Seasonal heat-pump COP',3,1,8,hint='Heat-pump share only; avoid double-counting losses included in a published rating.'),field('loss','Extra heat-loss allowance (%)',15,0,100,hint='Added to useful draw heat. Illustrative, not a measured tank loss.'),field('auxiliary','Heat supplied by resistance backup (%)',0,0,100,hint='Share of thermal load, not operating hours.'))+
 fields('Prices and baseline',select('currency','Display currency',[('USD','USD'),('EUR','EUR'),('GBP','GBP'),('CAD','CAD'),('AUD','AUD'),('JPY','JPY')],'Display only; no currency conversion or live prices.'),field('rate','Electricity price (currency/kWh)',0.20,0,10000),field('baselineRate','Baseline fuel/electricity price (currency/kWh)',0.20,0,10000,hint='Convert your bill units first. Fixed charges excluded.'),field('baselineEfficiency','Baseline useful-heat efficiency (%)',100,1,100,hint='100% is the resistance-heater example; change for a fuel-fired baseline.'),field('extra','Additional upfront cost (currency)',0,0,1000000,hint='Optional payback input: enter 0 to omit. Use a quote, not an assumed market price.')),
 '<h2>Annual heat and electricity</h2><p class="formula">Useful draw heat = litres/day × 4.186 × (delivered °C − inlet °C) ÷ 3,600 × days<br>Modelled heat = useful draw heat × (1 + loss % / 100)<br>Electricity = modelled heat × [(1 − backup fraction) / COP + backup fraction]</p><p>Water density is approximated as 1 kg/L; heat capacity is 4.186 kJ/(kg·°C). Backup heat is modelled at COP 1. The percentage-loss model scales with draw volume and does not represent fixed standing losses at zero draw. Days must be an integer from 1–366; COP 1–8 and the temperature bounds are model input limits, not equipment operating limits.</p><h2>Baseline and payback</h2><p class="formula">Baseline energy = modelled heat / baseline efficiency fraction<br>Annual saving = baseline energy × baseline price − electricity × electricity price<br>Simple payback = additional upfront cost / positive annual saving</p><p>No result is a quote or sizing recommendation. Fixed tariffs, finance, maintenance, space-conditioning effects, recovery capacity, hourly climate and price changes are excluded. Use the same thermal boundary for both systems. COP 2/3/4 rows are illustrative sensitivities. Defaults are examples only.</p>',
 'An annual energy total does not size a tank or prove that peak hot-water demand can be met. A published seasonal rating may already include some losses or backup heating.', ['DOE_HP','HP_DESIGN','HP_INSTALL'],'heat-pump-water-heaters')

toolpage('emergency-stockpile','Emergency stockpile and shopping calculator','Choose a planning period, count usable stock and see what remains to buy.','stockpile',
 fields('Household and planning horizon',field('people','People',4,1,1000,1),field('days','Days to cover',7,1,90,1,hint='Follow local guidance and your household needs.'))+
 fields('Daily planning allowances',select('waterPreset','Water reference',[('3','Japan example: 3 L drinking water'),('3.785411784','US CDC example: 1 US gallon'),('custom','Custom allowance')],'These references cover different uses. Read the source and adjust for your situation.'),field('waterRate','Water (L/person/day)',3,0.1,50,hint='Editing this field selects a custom allowance.'),field('mealRate','Individual meal portions/person/day',3,1,10,1,hint='Counting convention, not a nutritional prescription.'),field('toiletRate','Toilet uses/person/day',5,1,30,1,hint='Planning assumption; actual needs and product use counts vary.'))+
 fields('Usable supplies already stored',field('waterOwned','Water already stored (L)',0,0,1000000),field('mealsOwned','Individual meal portions already stored',0,0,1000000,1),field('toiletsOwned','Toilet uses already supplied',0,0,1000000,1),field('bottle','New water container capacity (L)',2,0.1,1000,hint='Used to round the shopping deficit up to whole containers.')),
 '<h2>Calculation</h2><p class="formula">Target = people × days × daily allowance<br>Additional supply = max(0, target − usable stock)<br>Water containers to add = round up(additional litres / container litres)</p><p>All people, days, meals and toilet-use counts are whole numbers. Fractional litres are allowed. Quantity limits prevent nonsensical input; they are not recommended preparedness limits. The Japan reference is about 3 L drinking water per person per day. The US reference is 1 US gallon = 3.785411784 L and has a different scope. Changing the water allowance selects Custom.</p><p>The tool does not assess water quality, nutrition, food-storage safety, allergies, pet needs, medical supplies, local sewer conditions or disposal rules. Toilet uses are not automatically equal to packages or bags. Confirm product yield and local guidance. Print a copy to keep your plan; nothing is saved.</p>',
 'A numerical target is not a complete emergency plan. Extra water for hygiene, pets, climate or individual needs may be required. Follow local emergency instructions.', ['STOCK','MAFF','CDC_WATER','TOILET_STOCK'],'emergency-preparedness')

toolpage('v2h-backup','V2H backup runtime calculator','Estimate an energy budget from usable battery capacity and a steady average AC load.','backup',
 fields('Battery energy',field('capacity','Usable battery capacity (kWh)',60,0.1,1000,hint='Use usable capacity, not a gross marketing capacity.'),field('start','Starting charge (%)',80,0,100),field('reserve','Reserve charge (%)',20,0,100,hint='Cannot exceed starting charge.'),field('efficiency','Battery-to-AC conversion efficiency (%)',90,1,100,hint='Example only; do not double-count standby here.'))+
 fields('Loads',field('load','Average connected AC load (W)',500,1,100000,hint='Average consumption, not just appliance nameplate totals.'),field('standby','Additional AC-equivalent system standby (W)',0,0,10000,hint='Add only losses not already included in efficiency.')),
 '<h2>Energy budget</h2><p class="formula">Available AC energy (kWh) = usable capacity × (starting % − reserve %) / 100 × efficiency % / 100<br>Runtime (hours) = available AC energy / [(average load W + standby W) / 1,000]</p><p>Equal starting and reserve charge gives zero usable energy. A greater reserve is rejected. Real loads cycle and equipment has surge and continuous-power limits. Capacity can change with age and temperature; state-of-charge reporting and usable-capacity boundaries may differ. No connector, vehicle, charger, inverter, transfer switch, islanding, solar charging or local grid approval is checked.</p>',
 'CHAdeMO’s bidirectional technology reference does not prove that your car supports home backup. Never infer safe household connection or life-critical runtime from this calculation.', ['CHADEMO'])

toolpage('parcel-locker','Parcel-locker capacity estimator','Use arrival rate and collection delay to explore an apartment locker scenario.','lockers',
 fields('Arrivals and collection',field('homes','Homes served',50,1,100000,1),field('rate','Parcels per home per week',2,0,1000,hint='Use actual site observations if available.'),field('hours','Mean collection delay (hours)',12,0,720,hint='Delivery to removal, including unattended periods.'))+
 fields('Chosen planning headroom',field('peak','Peak multiplier',1.6,1,20,hint='Arbitrary scenario assumption, not a measured national peak.'),field('utilisation','Target occupancy (%)',80,1,100,hint='Headroom assumption, not a service-level probability.')),
 '<h2>Steady-state planning model</h2><p class="formula">Mean daily arrivals = homes × parcels/home/week / 7<br>Mean occupied compartments = daily arrivals × mean collection hours / 24<br>Planning compartments = round up(mean occupied × peak multiplier / occupancy fraction)</p><p>This applies an average-flow relationship with additional chosen headroom. It assumes one parcel per compartment and steady flows. Zero arrivals or zero dwell time gives zero modelled occupancy; it does not prove that an actual installation needs no boxes. Inputs must be finite, with whole homes and positive occupancy. Target occupancy means the share of adjusted capacity planned to be filled; it is not a probability of finding a free box.</p><p>The model omits parcel size mix, multiple carriers, clustered arrivals, holidays, rejected parcels, maintenance, accessibility, fire routes and lock workflow. Collect hourly arrival and retrieval data, then ask a vendor for a design and service-level analysis. MLIT’s redelivery programme establishes the policy context, not the multipliers in this tool.</p>',
 'A planning compartment count is not a procurement specification. Compare longer collection delays and peak periods; check every relevant parcel-size class.', ['MLIT_DELIVERY','LOCKER_APT'])

page('about','About Everyday Japan Lab','Practical systems from everyday Japan, examined for use elsewhere.',f'''<article class="prose"><h2>What this site is for</h2><p>Everyday Japan Lab is an independent early-stage project published by Kouhei. It explores household equipment, routines and services used or developed in Japan, then asks which problems they could solve in other places.</p><p>We start with a practical question: will something fit, what conditions does it need, what might it cost to operate, or how much should a household plan for? The answer can be that a system is unsuitable for a particular home.</p><h2>What our work does and does not establish</h2><p>The current guides are desk research using linked public and manufacturer sources. We have not physically tested the linked products and do not certify installations. We distinguish sales reports, official recommendations and observed adoption. None alone proves that a system is common everywhere or superior to alternatives.</p><p>Initial drafting and code development use AI assistance. Sources, assumptions and calculation methods are provided for inspection. The publisher remains responsible for checking the material and resolving corrections.</p><h2>Independence</h2><p>This development preview has no advertising, sponsorship, paid rankings or affiliate links. Future commercial relationships will be identified visibly and will not determine editorial rankings. {link('advertising','Read the policy.')}</p><h2>Corrections and questions</h2><p>{link('contact','Use the contact and corrections page')} to report a specific claim, source or tool problem. Please include the page and the reason it needs attention.</p></article>''')
page('methodology','How we research and choose topics','Useful problems, explicit evidence and visible limits.',f'''<article class="prose"><h2>Start with a problem</h2><p>A topic needs a concrete reader decision and a useful output. Novelty alone is insufficient. We screen Japanese maturity, a specific overseas use case, search intent, purchase-stage questions, likely advertiser categories, possible affiliate fit, competition, tool usefulness, source availability and safety. These are separate judgements; we do not disguise them as a precise composite score.</p><h2>Distinguish kinds of evidence</h2><ul><li><strong>Public statistics:</strong> check the date, population and metric. Shipments are not installed households.</li><li><strong>Official recommendations:</strong> show what an agency advises, not how many people follow it.</li><li><strong>Manufacturer documents:</strong> establish a named product’s specification or the company’s own claim. They do not independently prove market size or comparative superiority.</li><li><strong>Editorial hypotheses:</strong> overseas demand, query ideas, competition and commercial fit remain hypotheses until validated with target-market evidence.</li></ul><h2>Use sources within their scope</h2><p>We prefer public agencies, standards bodies and original manufacturer documentation. A model-specific installation manual does not create a universal rule. We identify regional differences and review sources when content or tools change. {link('sources','The source register')} records scope and checked dates.</p><h2>Make calculators inspectable</h2><p>Each tool shows units, formulas, assumptions, input bounds and exclusions. Example values are not measured averages. Inputs are validated, changed inputs clear old results, and adverse outcomes such as negative savings remain visible. Calculators support planning rather than certifying health, safety or code compliance.</p><h2>Publish selectively</h2><p>The editorial inventory contains 110 screened candidates; it is not a claim that all 110 are proven opportunities or widely adopted in Japan. Only three themes have full guides at this stage. Topics with weak maturity evidence, difficult local verification or high harm potential are held back. We do not publish an article simply to fill a keyword list.</p><h2>Correct visibly</h2><p>Corrections should update the relevant page, its source or formula and its reviewed date. Material changes belong in the project change log. {link('contact','Report an issue')} with the affected page and supporting detail.</p></article>''')
page('privacy','Privacy — development preview','This notice describes the current GitHub Pages preview, not a future advertising site.','''<article class="prose"><h2>Who publishes this preview?</h2><p>Everyday Japan Lab is published by Kouhei. The contact page provides a public issue channel for editorial corrections and technical problems.</p><h2>Calculator inputs</h2><p>The five calculators run in your browser. This site’s code does not send their inputs to a server, store them in cookies or local storage, or create user accounts. Reloading the page discards the calculation. A printed or saved copy is under your control.</p><h2>Hosting and external links</h2><p>GitHub Pages serves this preview and may process technical request information under <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a>. Our lack of analytics tags does not mean the host receives no connection information. Following a source link or opening GitHub’s issue form takes you to another provider with its own practices.</p><h2>Advertising and measurement</h2><p>There are no AdSense ads, affiliate tracking links, GA4 tags, embedded videos or third-party web fonts in this preview. We do not request optional advertising or analytics consent for services we have not enabled.</p><h2>Feedback</h2><p>GitHub issues are public. Do not post private contact details, health information, account credentials or sensitive household information. A private contact route must be configured before inviting private enquiries.</p><h2>Future production site</h2><p>A Blogger production site will use a separate notice describing its actual platform and enabled services. Advertising or analytics will require an updated disclosure and appropriate consent arrangements before activation. This preview notice is not that production notice.</p><p>Last updated: 2026-09-24.</p></article>''')
page('contact','Contact and corrections','Help us improve a specific claim, source or calculation.','''<article class="prose"><h2>Report a correction or tool problem</h2><p><a class="button" href="https://github.com/kouheim1979/invest/issues/new?title=Everyday%20Japan%20Lab%3A%20">Open a GitHub issue</a></p><p>This opens a public form on GitHub and may require a GitHub account. Nothing is submitted automatically. Include the page URL, what appears incorrect, the result you expected and a primary source if you have one. For a calculation problem, use non-sensitive example inputs.</p><div class="callout caution"><p>Issues are public. Do not include personal contact details, payment information, health information or identifying photos. This development site does not yet offer a private enquiry channel.</p></div><h2>Editorial ownership</h2><p>Publisher: Kouhei / Everyday Japan Lab. We welcome corrections and local context. We cannot provide individual installation approval, emergency assistance or professional certification.</p><h2>Commercial enquiries</h2><p>No sponsorship or affiliate programme is currently active. A private contact route and written disclosure process will be established before accepting commercial enquiries.</p></article>''')
page('advertising','Advertising and affiliate policy','Editorial decisions are based on usefulness and evidence, not payment.','''<article class="prose"><h2>Current status</h2><p>This development preview carries no advertising, affiliate links or sponsored content. Ordinary manufacturer and public-source links are references, not paid recommendations.</p><h2>If monetization is introduced</h2><ul><li>Advertisements will be labelled and visually separated from navigation, calculator controls and results.</li><li>Affiliate relationships will be disclosed near the relevant links, with any programme-required site disclosure.</li><li>Sponsored articles will be labelled at the beginning and identify the sponsor.</li><li>Payment will not buy a recommendation rank or remove a material limitation.</li><li>We will not describe an untested product as tested or the best.</li><li>Manufacturer claims will remain attributed, with their test conditions where relevant.</li></ul><h2>Possible revenue sources</h2><p>Contextually relevant ads, approved retail affiliate programmes, qualified local service referrals and clearly labelled sponsorship may be considered. Programme availability and approval are not assumed. No revenue level is promised.</p><h2>Reader experience</h2><p>Tools must remain usable without confusing clicks or exaggerated urgency. Privacy information and any required consent choice must reflect the services actually enabled. Commercial suitability does not override safety or source quality.</p></article>''')
sourcekeys=list(dict.fromkeys(k for a in ARTICLES for k in a['refs']))+['CHADEMO','MLIT_DELIVERY','LOCKER_APT']
page('sources','Primary source register','What each reference can establish — and what it cannot.', '<article class="prose"><p>This register covers the published guides and tools. The broader candidate inventory has its own source table. All references were checked on 2026-09-24; linked providers may change their documents.</p></article>',refs=list(dict.fromkeys(sourcekeys)))
(ROOT/'research/page-manifest.json').write_text(json.dumps(PAGES,ensure_ascii=False,indent=2)+'\n')
print(f'Built {len(PAGES)} pages; all development pages retain noindex,nofollow.')
