"""Original English editorial content. Sources support identified facts, not product endorsements."""
ARTICLES = [
dict(slug='bidet-seats',title='Japanese bidet seats: what to check before buying',tag='Bathroom / Buying guide',deck='A warm-water wash can be useful. The buying decision starts with your toilet, local utilities and the exact seat drawing.',refs=['TOTO_HISTORY','TOTO_FIT','BRONDELL_FIT','BRONDELL_MANUAL'],tool='washlet-fit',body='''
<h2>What is a Japanese bidet seat?</h2>
<p>An electric bidet seat replaces a toilet seat and adds a water-washing function. Depending on the model, it may heat water, warm the seat or offer a dryer. A non-electric attachment is a different product category with different requirements. WASHLET is TOTO’s trademark; “bidet seat” is the generic term used here.</p>
<p>TOTO dates WASHLET’s introduction to 1980 and reported cumulative worldwide sales of 70 million units in November 2025. That is a manufacturer-reported sales milestone across products and countries, not the number of Japanese households with a seat. The same release describes expanding overseas sales. It supports a long-established product category, not a claim that every Japanese home has one. <a href="#sources">[1]</a></p>
<h2>Which problem does it solve?</h2>
<p>It gives a household a washing option at an existing toilet without adding a separate bidet fixture. Whether that is useful depends on personal preference, the room and the effort needed to install and maintain it. Comfort features can be attractive, but additional electronics also bring cleaning tasks, energy use and eventual repair or replacement.</p>
<p>The Japanese example is useful because the equipment has evolved over decades. It does not establish that a Japanese domestic-market model is the right purchase abroad. A locally supported model, a simpler attachment or keeping the existing seat can each be a reasonable outcome.</p>
<h2>Start with the toilet, not the feature list</h2>
<p>Record the toilet manufacturer and model if visible. Measure from the mounting-bolt centre line to the front of the bowl, the bolt spacing and the space behind the bolts. Photograph the tank-to-bowl transition and the underside of the mounting holes. Compare this record with the chosen seat’s installation drawing.</p>
<p>TOTO’s fit chart separates models and bowl shapes and flags interfering contours. Brondell also publishes a dedicated fit guide. These are useful evidence that a general “round” or “elongated” description cannot settle every fit question. Our worksheet records the measurements; it does not turn one generic length threshold into a pass. <a href="#sources">[2, 3]</a></p>
<div class="callout"><p><strong>A practical stopping point:</strong> if the manufacturer cannot confirm the drawing against your toilet, resolve that question before ordering. Return costs and installed-product restrictions can make a speculative purchase inconvenient.</p></div>
<h2>Electrical and plumbing checks come next</h2>
<p>Compare the exact product’s voltage and frequency rating with the local supply. Confirm grounding, required protective devices, outlet placement, circuit capacity and the manufacturer’s cable-routing instructions with a qualified local installer. A plug that physically fits does not establish electrical compatibility.</p>
<p>On the water side, confirm the shut-off valve, thread and hose arrangement, permitted supply pressure and any local backflow-protection requirement. Follow the manual supplied for that model and market. The linked Brondell manual is a concrete example of product-specific installation conditions, not a substitute for another manufacturer’s instructions. <a href="#sources">[4]</a></p>
<h2>Features worth comparing — and their trade-offs</h2>
<div class="table-scroll"><table><thead><tr><th>Question</th><th>Why it affects the decision</th></tr></thead><tbody><tr><td>Does the seat fit comfortably?</td><td>The housing can change the usable seating space. Dimensions and a suitable return policy matter.</td></tr><tr><td>Can everyone use the controls?</td><td>Reach, readable labels and a remote’s location may matter more than the number of settings.</td></tr><tr><td>Who will maintain it?</td><td>Check cleaning access, filters, consumables and available service.</td></tr><tr><td>What happens without power?</td><td>Confirm which functions remain available in the specific toilet/seat combination.</td></tr><tr><td>Is local support available?</td><td>Imported domestic models may have unsuitable ratings, instructions or warranty coverage.</td></tr></tbody></table></div>
<h2>How much electricity will it use?</h2>
<p>A nameplate’s rated power is not an average daily load. Water heating, seat settings, room temperature, standby behaviour and usage all affect consumption. Use a model’s declared energy figure with its test conditions, or a suitable measurement method approved for the installation. Annual running cost is annual measured kWh multiplied by the relevant electricity price. We do not apply a universal wattage to every seat.</p>
<h2>Your buying sequence</h2>
<ol><li>Choose the functions you actually need and a locally supported product range.</li><li>Record the toilet’s dimensions and contour; compare the exact fit drawing.</li><li>Get unresolved electrical and plumbing questions checked.</li><li>Compare the full installed cost, maintenance and return terms.</li><li>Keep the manual and model number for future cleaning and service.</li></ol>
<p>This guide is desk research. We have not physically tested or certified the linked products, and the links are not paid placements.</p>
'''),
dict(slug='bidet-seats/measure',title='Will a bidet seat fit? A measurement worksheet',tag='Bathroom / Fit',deck='Measure the mounting points and the shape around them. Use the drawing for the exact seat you intend to buy.',refs=['TOTO_FIT','BRONDELL_FIT'],tool='washlet-fit',body='''
<h2>Make one record for the existing toilet</h2>
<ol><li>Write down the toilet’s manufacturer and model. A photograph of a label is more reliable than remembering the bowl’s appearance.</li><li>Measure from the centre line of the seat mounting bolts to the front edge of the bowl.</li><li>Measure the bolt holes from centre to centre.</li><li>Measure the space behind the bolt centre line toward the tank, and record the curved or raised surfaces in that area.</li><li>Check whether the underside of the holes is accessible or whether the toilet needs a particular mounting arrangement.</li></ol>
<p>Use the same units for the toilet and product drawing. One inch equals 25.4 mm exactly. Record a sensible measurement tolerance instead of treating a rough tape measurement as millimetre-perfect.</p>
<h2>Round versus elongated is only a starting label</h2>
<p>The linked US fit charts distinguish bowl shapes, but the housing and mounting arrangement also matter. Do not use a generic US shape name for a toilet sold elsewhere without checking the outline. A tank can interfere with a seat even when a front-to-back dimension looks plausible. <a href="#sources">[1, 2]</a></p>
<h2>Compare like with like</h2>
<div class="table-scroll"><table><thead><tr><th>Your record</th><th>Compare against</th></tr></thead><tbody><tr><td>Bolt-centre-to-front length</td><td>The dimension measured from the same reference points in the seat drawing</td></tr><tr><td>Bolt spacing and mounting access</td><td>The permitted mounting range and supplied hardware</td></tr><tr><td>Rear clearance and contour</td><td>The housing envelope and any excluded toilet shapes</td></tr><tr><td>Hose and cable path</td><td>Clear routes that comply with the installation manual</td></tr></tbody></table></div>
<h2>What the checker does</h2>
<p>The free worksheet converts your measurements to millimetres and creates an unresolved-check list. It intentionally has no “fits all toilets” rule. Matching measurements still leave material condition, mounting access, supply requirements and product approval to verify.</p>
<p>For a useful manufacturer enquiry, attach the measurement record, the toilet model, the proposed seat model and photographs of the tank contour and mounting area. Remove personal information from photographs before sharing them.</p>
'''),
dict(slug='bidet-seats/electrical-plumbing',title='Bidet seat electricity and plumbing: questions for your installer',tag='Bathroom / Installation readiness',deck='A shopping checklist for local professional verification, with a simple way to think about running cost.',refs=['BRONDELL_MANUAL','TOTO_FIT'],tool='washlet-fit',body='''
<h2>Read the rating for the actual market</h2>
<p>Find the voltage, frequency, current or power rating and installation manual for the exact model being sold. A similar model name in another country may have a different specification. Ask whether the product is approved and supported in the country where it will be installed.</p>
<p>Use the manual to prepare a question list: Is the supply appropriate? Is the outlet correctly grounded and protected? Is its location acceptable in this bathroom? Does the circuit have the needed capacity? Can the cord reach without violating the instructions? These are local installation questions, not a generic website approval. The reference manual illustrates how product-specific these instructions are. <a href="#sources">[1]</a></p>
<h2>Check the water connection as a system</h2>
<p>Record the shut-off valve type, accessible connection space and the specified pressure range. Have an installer confirm thread compatibility, the permitted supply connection and any required backflow arrangement. Do not force a connector that merely appears to fit. Confirm the manufacturer’s leak-check and maintenance instructions before use.</p>
<h2>Estimate operating cost from energy, not peak power</h2>
<p class="formula">Annual cost = measured or declared annual energy (kWh/year) × your electricity rate (currency/kWh)</p>
<p>For an illustrative calculation only, 100 kWh per year at 0.20 currency units per kWh costs 20 currency units per year. Neither input is a typical bidet consumption or current tariff claim. If a bill has time-of-use prices, a single average price simplifies the calculation.</p>
<p>Do not multiply peak nameplate watts by 24 hours unless the device actually draws that load continuously. Heating and standby behaviour differ. Use a measurement method suitable for the rated load and bathroom installation; do not introduce an unsafe temporary electrical arrangement to obtain a reading.</p>
<h2>Decide what remains unresolved</h2>
<p>The readiness worksheet distinguishes unknown supply ratings, a known voltage mismatch and unverified outlet or valve conditions. Even a matching voltage label is only one check. Keep physical fit, electrical approval and plumbing approval as separate questions so that a favourable answer to one does not conceal a problem with another.</p>
'''),
dict(slug='heat-pump-water-heaters',title='Heat-pump water heaters: what Japan’s EcoCute experience can teach',tag='Energy / Decision guide',deck='Compare a water-heating system against your household’s demand, installation conditions and local energy prices.',refs=['JRAIA','IEA_HP','DOE_HP','HP_DESIGN','HP_INSTALL'],tool='heat-pump-water-heater',body='''
<h2>What is the useful idea?</h2>
<p>A heat-pump water heater uses electricity to move heat into stored water. Its heat output can exceed its electrical input because it also draws heat from its surroundings. This differs from an electric resistance element that converts electrical energy directly into heat. The ratio is often described as a coefficient of performance, or COP. <a href="#sources">[3]</a></p>
<p>For a household, the question is practical: can the system supply enough hot water at an acceptable installed and operating cost, in the available space? A high efficiency figure alone cannot answer that question.</p>
<h2>What is established in Japan?</h2>
<p>EcoCute is a Japanese category associated with CO2-refrigerant heat-pump water heating. The Japanese industry association reported cumulative shipments exceeding ten million in March 2025. IEA’s 2026 market review describes Japan as a mature heat-pump market and discusses CO2 water heating. Shipment history supports an established industry, not a claim that every household uses EcoCute. <a href="#sources">[1, 2]</a></p>
<p>The transferable lesson is to consider hot-water storage, heat-pump performance and household demand together. It is not an instruction to import a Japanese 100 V or 200 V appliance. A locally approved system with service support is the relevant comparison.</p>
<h2>Do not confuse different system layouts</h2>
<div class="table-scroll"><table><thead><tr><th>Layout</th><th>What to investigate</th></tr></thead><tbody><tr><td>Outdoor heat-pump unit with separate storage tank</td><td>Outdoor siting, climate rating, noise, pipe runs, freeze protection and tank location</td></tr><tr><td>Integrated indoor heat-pump tank</td><td>Room air volume or ducting, airflow, condensate disposal and interaction with space conditioning</td></tr><tr><td>Resistance backup within a heat-pump system</td><td>When it operates, what demand it supports and its effect on seasonal energy use</td></tr></tbody></table></div>
<p>US ENERGY STAR guidance for integrated units discusses installation conditions such as air supply and the surrounding space. Those requirements should not be copied wholesale onto a split CO2 system. Read the manual and local installation guidance for the system actually under consideration. <a href="#sources">[4, 5]</a></p>
<h2>Build a comparison from useful hot water</h2>
<p>Estimate the daily volume of delivered warm water and the temperature rise from the cold inlet. The calculator converts that demand into useful thermal energy, adds an explicit heat-loss allowance, and divides the heat-pump share by an assumed seasonal COP. Resistance backup is counted separately at COP 1.</p>
<p>“Delivered temperature” means the mixed water at the point of use in this model. It is not a recommended tank setpoint. Tank temperature, hygiene control, scald protection and mixing arrangements must follow local requirements and the manufacturer. This distinction prevents a volume of mixed shower water from being mistaken for an equal volume of hotter stored water.</p>
<h2>Why the cheapest result may not be the best decision</h2>
<p>A low modelled bill does not include every cost. Consider installation work, available tank sizes, peak demand, recovery time, service access, noise, warranties and repair arrangements. An indoor unit’s effect on space heating or cooling may also matter. The calculator excludes those interactions; a local assessment can investigate them.</p>
<p>Use the same service boundary for the baseline. A gas price per billing unit must be converted into the energy unit used in the tool, and the efficiency must describe the same useful-heat boundary. Fixed charges are not included. Removing a gas appliance does not automatically remove the household’s entire gas standing charge.</p>
<h2>A useful quote request</h2>
<ol><li>Give the installer your household’s hot-water pattern and any unusually concentrated demand.</li><li>Document the proposed unit and tank locations, electrical supply and service access.</li><li>Ask which performance data apply to your climate and selected operating mode.</li><li>Ask when backup heating operates and how the quoted capacity meets peak demand.</li><li>Compare full installed cost and the assumptions behind projected energy use.</li></ol>
<p>Our calculator is a transparent scenario model, not a product sizing engine, installer quote or promise of savings. No linked product has been physically tested by this site.</p>
'''),
dict(slug='heat-pump-water-heaters/installation',title='Heat-pump water heater installation: a pre-quote checklist',tag='Energy / Site readiness',deck='Collect the information an installer needs before comparing equipment prices.',refs=['HP_DESIGN','HP_INSTALL','DOE_HP'],tool='heat-pump-water-heater',body='''
<h2>Identify the system layout first</h2>
<p>Write down whether the proposed equipment has an indoor integrated heat pump or a separate outdoor unit. This determines which air, condensate, weather and noise questions need attention. A generic room-volume rule is not reliable across all models.</p>
<h2>Record the site conditions</h2>
<ul><li><strong>Access:</strong> doorway, stairs, installation footprint and room for future service or replacement.</li><li><strong>Air and location:</strong> manufacturer-required airflow or ducting, permissible temperatures and any acoustic concerns.</li><li><strong>Water and drainage:</strong> pipe connections, condensate routing, pressure-control arrangements and safe drainage as applicable.</li><li><strong>Electrical supply:</strong> the exact rating, circuit requirements and local product approval.</li><li><strong>Demand:</strong> household routines, simultaneous hot-water use and the required recovery performance.</li></ul>
<p>The ENERGY STAR design and installation resources address integrated heat-pump water heaters and illustrate why airflow and placement belong in the decision. Use those resources within their intended product and market context. An installer must verify the actual model’s instructions. <a href="#sources">[1, 2]</a></p>
<h2>Ask for an explanation of backup operation</h2>
<p>A quote should identify the operating mode used for an energy estimate. Ask what happens during high demand or unfavourable conditions and whether resistance heating supplies part of the load. If that share is unknown, compare scenarios instead of assuming it is zero.</p>
<h2>Keep the limits visible</h2>
<p>This checklist does not select a tank capacity, certify a room, prescribe a temperature or approve electrical work. It organizes observations for a professional. Our calculator models annual energy; matching an annual total does not show that the heater can meet the busiest hour of the day.</p>
<p>A practical comparison includes the installed price, required alterations, expected service life information from the supplier, maintenance, warranty coverage and local repair availability. Record exclusions in each quote so that unlike packages are not compared as though they were identical.</p>
'''),
dict(slug='heat-pump-water-heaters/cop-and-cost',title='COP, heat loss and hot-water cost: understand the calculator',tag='Energy / Calculation method',deck='Follow the units and change one assumption at a time.',refs=['DOE_HP','HP_DESIGN'],tool='heat-pump-water-heater',body='''
<h2>Start with the water’s temperature rise</h2>
<p>For an approximate household model, take water density as 1 kg per litre and specific heat capacity as 4.186 kJ per kg per °C. Heating V litres through a temperature rise ΔT requires V × 4.186 × ΔT ÷ 3,600 kWh of useful heat. These are physical modelling assumptions, not appliance test results.</p>
<p>At 200 litres per day and a 25 °C rise, this is about 5.8 kWh of useful heat per day. This is an illustrative demand, not a national average.</p>
<h2>Define the heat-loss boundary</h2>
<p>The tool adds a user-entered percentage to useful draw heat. A 15% input means modelled heat generation is 1.15 times useful draw heat. It does not mean that 15% of input electricity disappears, and it is not a measured loss rate for any product. A real installation may need a different model, especially at very low hot-water use.</p>
<h2>Separate heat-pump and resistance heat</h2>
<p class="formula">Electricity = modelled heat × [(1 − resistance heat fraction) ÷ seasonal COP + resistance heat fraction]</p>
<p>The resistance share is a fraction of heat supplied, not a fraction of operating hours. The heat-pump COP input should represent the selected performance boundary. If published seasonal data already include backup heating or tank losses, do not add those effects again. Consult the rating’s definition or set the additional allowances appropriately.</p>
<h2>Compare the baseline honestly</h2>
<p>Baseline energy equals the same modelled heat divided by baseline efficiency. Multiply each energy input by its own price per kWh. A negative saving means the heat-pump scenario costs more under those assumptions. The tool deliberately allows that outcome.</p>
<p>Simple payback divides a positive additional upfront cost by a positive annual saving. It ignores financing, maintenance, future tariffs, replacement and residual value. If the saving is zero or negative, or no extra cost is provided, it reports no payback rather than inventing a break-even date.</p>
<h2>What the model leaves out</h2>
<p>It does not simulate hourly weather, draw patterns, storage recovery, solar self-consumption, demand charges, plumbing circulation or interactions with space conditioning. COP sensitivity at 2, 3 and 4 is a scenario comparison, not a promised operating range. Manufacturer performance data and local design review are the next sources to use.</p>
'''),
dict(slug='emergency-preparedness',title='Rolling stock: build emergency supplies from things you already use',tag='Preparedness / Household planning',deck='Count what you have, fill the gaps and keep it moving through everyday use.',refs=['STOCK','MAFF','CDC_WATER','TOILET_STOCK'],tool='emergency-stockpile',body='''
<h2>What does “rolling stock” mean here?</h2>
<p>It means holding an extra supply of suitable everyday food, using the older items in normal meals and replacing them. Japan’s agriculture ministry explains this approach as part of household food preparedness. It is a public recommendation and a useful planning method; we do not have evidence that every Japanese household follows it. <a href="#sources">[2]</a></p>
<p>The practical problem is familiar: a box bought for emergencies can be forgotten, while an everyday pantry may have too little reserve. Rotation connects the reserve to an existing shopping routine. It can also reveal foods that the household would not actually eat before a stressful situation occurs.</p>
<h2>Choose a planning horizon deliberately</h2>
<p>Japan’s Cabinet Office advises at least three days of household supplies and preferably a week. Local hazards, access and public guidance may call for a different period. The calculator accepts a chosen number of days rather than presenting one quantity as sufficient for every disaster. <a href="#sources">[1]</a></p>
<p>A smaller plan that fits the home can be a starting point, not proof of complete readiness. Review the needs of people who are away during the day, visitors, pets and anyone who depends on particular supplies. Keep individualized health or dietary advice with the appropriate professional.</p>
<h2>Separate four decisions</h2>
<div class="table-scroll"><table><thead><tr><th>Decision</th><th>Question to resolve</th></tr></thead><tbody><tr><td>Water</td><td>Which local guideline applies, and what uses does its allowance include?</td></tr><tr><td>Food</td><td>Can the household eat and prepare it during the likely outage?</td></tr><tr><td>Sanitation</td><td>What can be used if water or sewer service is unavailable?</td></tr><tr><td>Storage and rotation</td><td>Can supplies be reached, inspected and replaced without blocking routes?</td></tr></tbody></table></div>
<h2>Count the reserve you already own</h2>
<p>Our calculator uses people × days × a daily allowance, then subtracts usable stock. A water deficit is rounded up to whole containers of the chosen capacity. Meal portions and toilet uses are counted separately. A package labelled “ten servings” should not automatically be entered as ten complete individual meals.</p>
<p>Count only items that can serve the intended purpose. Food that requires unavailable cooking equipment is different from ready-to-eat food. A water container with an unknown condition is different from a verified usable supply. The arithmetic cannot judge those qualities for you.</p>
<h2>Do not transfer water guidelines without their scope</h2>
<p>The Japanese planning reference uses approximately 3 litres of drinking water per person per day. CDC’s US guidance uses at least one US gallon per person per day and discusses several uses, including drinking and cooking. These are not identical allowances with different unit labels. The tool offers both as labelled starting points and permits a custom rate. <a href="#sources">[1, 3]</a></p>
<h2>Include a sanitation plan</h2>
<p>Japan’s disaster-toilet materials use five toilet visits per person per day as a planning assumption. Actual needs vary. The calculator returns uses to supply; one use does not necessarily equal one complete package or one particular product’s bag. Confirm the product instructions, waste storage and local disposal guidance. It does not tell you whether a damaged sewer is safe to use. <a href="#sources">[4]</a></p>
<h2>Make the routine easy to keep</h2>
<ol><li>List food and supplies the household already uses and can store appropriately.</li><li>Record quantities and the nearest date needing attention.</li><li>Place older suitable stock where it will be used first.</li><li>Replace used reserve items during normal shopping.</li><li>Review the plan when the household, season or local guidance changes.</li></ol>
<p>This is a quantity and shopping tool, not a complete emergency plan, nutritional assessment or assurance that supplies will be adequate. Local official instructions take priority during an incident.</p>
'''),
dict(slug='emergency-preparedness/water',title='Emergency water: compare the Japanese and US planning allowances',tag='Preparedness / Water',deck='Different allowances cover different needs. Pick a local starting point before multiplying litres.',refs=['STOCK','CDC_WATER'],tool='emergency-stockpile',body='''
<h2>Two references, two contexts</h2>
<div class="table-scroll"><table><thead><tr><th>Reference</th><th>Planning amount</th><th>What to remember</th></tr></thead><tbody><tr><td>Japan, Cabinet Office</td><td>About 3 L per person per day for drinking water</td><td>Do not assume this covers all washing, toilet or other household water.</td></tr><tr><td>United States, CDC</td><td>At least 1 US gallon per person per day; at least 3 days, with 2 weeks if possible</td><td>Read the current guidance for its included uses and circumstances requiring more.</td></tr></tbody></table></div>
<p>One US liquid gallon is 3.785411784 litres. We use that conversion in the calculator; the extra digits improve unit conversion, not certainty about a person’s needs. The two source allowances are not interchangeable claims of sufficient water for every household. <a href="#sources">[1, 2]</a></p>
<h2>Count containers after subtracting usable stock</h2>
<p>For an illustrative four-person, seven-day plan at 3 L per person per day, the target is 84 L. With 20 L already available, the gap is 64 L. At 2 L per bottle that is 32 additional bottles. If the gap is not a whole number of containers, round up.</p>
<p>Think about how the containers will be moved and accessed. Storing the entire reserve behind heavy furniture may make counting easy while making use difficult. Keep evacuation routes clear and ask for local advice if storage weight or structural loading is a concern.</p>
<h2>Storage quality is a separate check</h2>
<p>Use the current public-health guidance for suitable containers, labelling, storage and replacement. Follow the dates and instructions for commercially bottled water. A quantity calculator cannot decide whether water remains safe. We do not provide improvised disinfection recipes or treat appearance as a safety test.</p>
<p>Plan additional needs explicitly, including pets and any local conditions the guideline identifies. Enter a custom rate when appropriate, and write down the source or reason so that the next household review can understand the number.</p>
'''),
dict(slug='emergency-preparedness/rotation',title='A practical pantry rotation and outage checklist',tag='Preparedness / Routine',deck='Build a reserve that is visible, usable and easy to replenish.',refs=['MAFF','STOCK','TOILET_STOCK'],tool='emergency-stockpile',body='''
<h2>Use a small inventory</h2>
<p>A useful record needs an item name, quantity, location, the next date to check and whether preparation requires water, heat or electricity. A complicated inventory that nobody updates can be less useful than a short list kept near the cupboard.</p>
<p>MAFF’s rolling-stock guidance connects ordinary consumption with replenishment. Our suggested inventory is an editorial way to apply that idea, not a government-approved template. <a href="#sources">[1]</a></p>
<h2>Keep quantity and usefulness separate</h2>
<ul><li>Count individual meals rather than assuming each package is a full meal.</li><li>Identify which items need cooking and whether the necessary safe preparation method is available.</li><li>Check household preferences and dietary requirements without treating the calculator as nutrition advice.</li><li>Place older appropriate stock in the normal use path and replace what is taken from the reserve.</li><li>Set a review routine that someone in the household will actually maintain.</li></ul>
<h2>Remember non-food supplies</h2>
<p>Record sanitation products, lighting and other locally recommended household supplies separately. For toilet products, note supported uses per package, storage instructions and the local waste-disposal plan. Five uses per person per day is a planning input in the Japanese source, not a prediction of every individual’s needs. <a href="#sources">[2, 3]</a></p>
<h2>A short review sheet</h2>
<div class="table-scroll"><table><thead><tr><th>Check</th><th>Record</th></tr></thead><tbody><tr><td>Who is covered?</td><td>People, days, pets and special supply requirements</td></tr><tr><td>What is usable now?</td><td>Current quantities and storage condition</td></tr><tr><td>What is missing?</td><td>Calculator deficits plus items outside the calculation</td></tr><tr><td>Who will replenish it?</td><td>A named household task and review date</td></tr><tr><td>What changed?</td><td>Season, household, local hazards or official advice</td></tr></tbody></table></div>
<p>You can print the calculator with the chosen inputs and results. It saves nothing in an account or browser storage, so keep a copy if you need a record. Avoid writing personal health information into a public issue or feedback channel.</p>
''')
]
